// Evidence Vault i18n strings - extracted to reduce main page file size

export const DOC_TYPE_CONFIG = {
  lease: {
    label_en: 'Lease', label_th: 'สัญญาเช่า', label_zh: '租约', label_ja: '賃貸契約', label_ko: '임대 계약', label_ru: 'Договор аренды',
    color: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-900 dark:text-emerald-100', bgColor: '#0C3B2E'
  },
  receipt: {
    label_en: 'Receipt', label_th: 'ใบเสร็จ', label_zh: '收据', label_ja: '領収書', label_ko: '영수증', label_ru: 'Квитанция',
    color: 'bg-gray-100 text-gray-700 dark:bg-gray-700 dark:text-gray-100', bgColor: '#64748B'
  },
  photo: {
    label_en: 'Photo', label_th: 'รูปภาพ', label_zh: '照片', label_ja: '写真', label_ko: '사진', label_ru: 'Фото',
    color: 'bg-gray-100 text-gray-700 dark:bg-gray-700 dark:text-gray-100', bgColor: '#64748B'
  },
  video: {
    label_en: 'Video', label_th: 'วิดีโอ', label_zh: '视频', label_ja: '動画', label_ko: '비디오', label_ru: 'Видео',
    color: 'bg-gray-100 text-gray-700 dark:bg-gray-700 dark:text-gray-100', bgColor: '#64748B'
  },
  letter: {
    label_en: 'Letter', label_th: 'จดหมาย', label_zh: '信件', label_ja: 'レター', label_ko: '편지', label_ru: 'Письмо',
    color: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-900 dark:text-emerald-100', bgColor: '#0C3B2E'
  },
  other: {
    label_en: 'Other', label_th: 'อื่น ๆ', label_zh: '其他', label_ja: 'その他', label_ko: '기타', label_ru: 'Прочее',
    color: 'bg-gray-100 text-gray-700 dark:bg-gray-700 dark:text-gray-100', bgColor: '#64748B'
  }
};

export function getDocTypeLabel(type, language) {
  const config = DOC_TYPE_CONFIG[type] || DOC_TYPE_CONFIG.other;
  return language === 'zh' ? config.label_zh :
    language === 'ja' ? config.label_ja :
    language === 'ko' ? config.label_ko :
    language === 'th' ? config.label_th :
    language === 'ru' ? config.label_ru :
    config.label_en;
}

const stringsAll = {
  en: {
    back: "Back to Dashboard", title: "Evidence Vault", subtitle: "Secure storage for all your rental documentation",
    uploadFiles: "Upload Files", uploadDocument: "Upload Document", uploadEvidence: "Upload evidence",
    documentType: "Document Type", customLabel: "Custom Label", customLabelPlaceholder: "e.g., Move-in photos",
    selectFiles: "Drag & drop files here or click to browse",
    supportedFormats: "PDF, Images (JPG, PNG), Videos (MP4, MOV, AVI)",
    selectedFiles: "Selected Files", uploadButton: "Upload", uploading: "Uploading...",
    recentUploads: "Recent Uploads", viewTemplates: "View Templates",
    viewTemplatesDesc: "Professional letter templates for common rental situations.",
    noDocuments: "No Documents Yet",
    noDocumentsDesc: "Start building your evidence vault for better protection. All your uploaded documents are securely stored here.",
    uploadFirst: "Upload First Document", deleteConfirm: "Are you sure?",
    confirmDelete: "Are you sure you want to delete this letter? This action cannot be undone.",
    confirmBulkDelete: "Are you sure you want to delete {count} file(s)?",
    view: "View", download: "Download", sendEmail: "Send Email", delete: "Delete",
    selectAll: "Select All", deleteSelected: "Delete Selected", deleting: "Deleting...", selected: "selected",
    storageUsed: "Storage: ~{used}MB / {limit}MB", filesUsed: "{count} / {limit} files",
    editDocument: "Edit Document", save: "Save", cancel: "Cancel", saving: "Saving...",
    loadingDocuments: "Loading documents...", exportZip: "Export as ZIP", exportReport: "Export Full Report",
    exporting: "Exporting...", bulkActions: "Bulk Actions", annotate: "Annotate",
    selectFile: "Please select files to upload.", uploadFailed: "Upload failed. Please try again.",
    error: "Error", fileSelected: "file selected", filesSelected: "files selected",
    preparing: "Preparing upload...", compressing: "Compressing images...",
    uploadingFiles: "Uploading files...", savingDocuments: "Saving documents...",
    uploadTypeLabel: "Document Type", customLabelLabel: "Custom Label (Optional)",
    refreshed: "Refreshed successfully", deleteSuccess: "Document deleted", uploadSuccess: "Upload successful",
    annotationSaved: "Annotation saved", annotationFailed: "Failed to save annotation",
    exportSuccess: "Export started", exportFailed: "Export failed",
    editSuccess: "Document updated successfully", editFailed: "Failed to update document",
    deleteFailed: "Failed to delete document", pleaseSelectDocuments: "Please select documents",
    downloadFailed: "Failed to download file",
    noEvidenceTitle: "No evidence uploaded yet",
    noEvidenceDescription: "Upload photos, videos and documents now so you have a time-stamped record if there's a dispute later.",
    upgradeVaultStorage: "Upgrade for full vault storage",
    addVoiceNote: "Add Voice Note", addVideo: "Add Video (Secure required)",
    voiceNotesAdded: "voice note(s)", videosAdded: "video(s)",
    upgradeToSecureVideo: "Upgrade to Secure for video evidence",
    upgradeToSecureVideoDesc: "Secure members can upload videos for stronger dispute cases.",
    upgradeToSecure: "Upgrade to Secure", upgradeTitle: "Video uploads require Secure",
    upgradeDescription: "Video evidence is only available on the Secure plan. Upgrade now to unlock:",
    upgradeBenefitUnlimitedScans: "• Unlimited lease scans",
    upgradeBenefitPriorityQueue: "• Priority case handling",
    upgradeBenefitVideoEvidence: "• Video evidence uploads",
    upgradeBenefitFullSupport: "• Comprehensive support",
    maybeLater: "Maybe later", maxVoiceReached: "Maximum 3 voice notes", maxVideoReached: "Maximum 3 videos",
    fileTooLarge: "File too large", voiceMaxSize: "Voice notes must be under 5MB",
    videoMaxSize: "Videos must be under 80MB", uploadVideo: "Upload Video", recordVideo: "Record Video",
    defaultDocLabel: "{docType} - {date}", dear: "Dear", closingRegards: "Warm regards",
    letterExtractionFailed: "[Letter content could not be extracted]", createdBy: "Created by",
    selectFromDevice: "Select from device", useCameraToRecord: "Use camera to record",
    imagesOptimizedDesc: "{count} images optimized, saved {saved}MB",
  },
  th: {
    back: "กลับไปยังแดชบอร์ด", title: "คลังหลักฐาน", subtitle: "จัดเก็บเอกสารการเช่าทั้งหมดของคุณอย่างปลอดภัย",
    uploadFiles: "อัปโหลดไฟล์", uploadDocument: "อัปโหลดเอกสาร", uploadEvidence: "อัปโหลดหลักฐาน",
    documentType: "ประเภทเอกสาร", customLabel: "ป้ายกำกับที่กำหนดเอง", customLabelPlaceholder: "เช่น รูปภาพตอนย้ายเข้า",
    selectFiles: "ลากและวางไฟล์ที่นี่หรือคลิกเพื่อเลือก",
    supportedFormats: "PDF, รูปภาพ (JPG, PNG), วิดีโอ (MP4, MOV, AVI)",
    selectedFiles: "ไฟล์ที่เลือก", uploadButton: "อัปโหลด", uploading: "กำลังอัปโหลด...",
    recentUploads: "อัปโหลดล่าสุด", viewTemplates: "ดูเทมเพลต",
    viewTemplatesDesc: "เทมเพลตจดหมายมืออาชีพสำหรับสถานการณ์การเช่าทั่วไป",
    noDocuments: "ยังไม่มีเอกสาร",
    noDocumentsDesc: "เริ่มสร้างคลังหลักฐานเพื่อการป้องกันที่ดีขึ้น เอกสารทั้งหมดที่คุณอัปโหลดจะถูกจัดเก็บอย่างปลอดภัยที่นี่",
    uploadFirst: "อัปโหลดเอกสารแรก", deleteConfirm: "คุณแน่ใจหรือไม่?",
    confirmDelete: "คุณแน่ใจหรือไม่ว่าต้องการลบจดหมายนี้? การกระทำนี้ไม่สามารถยกเลิกได้",
    confirmBulkDelete: "คุณแน่ใจหรือไม่ว่าต้องการลบไฟล์ {count} ไฟล์?",
    view: "ดู", download: "ดาวน์โหลด", sendEmail: "ส่งอีเมล", delete: "ลบ",
    selectAll: "เลือกทั้งหมด", deleteSelected: "ลบที่เลือก", deleting: "กำลังลบ...", selected: "เลือกแล้ว",
    storageUsed: "พื้นที่: ~{used}MB / {limit}MB", filesUsed: "{count} / {limit} ไฟล์",
    editDocument: "แก้ไขเอกสาร", save: "บันทึก", cancel: "ยกเลิก", saving: "กำลังบันทึก...",
    loadingDocuments: "กำลังโหลดเอกสาร...", exportZip: "ส่งออกเป็น ZIP", exportReport: "ส่งออกรายงานฉบับเต็ม",
    exporting: "กำลังส่งออก...", bulkActions: "การดำเนินการจำนวนมาก", annotate: "เขียนบันทึก",
    selectFile: "โปรดเลือกไฟล์ที่จะอัปโหลด", uploadFailed: "อัปโหลดไม่สำเร็จ โปรดลองอีกครั้ง",
    error: "ข้อผิดพลาด", fileSelected: "ไฟล์ที่เลือก", filesSelected: "ไฟล์ที่เลือก",
    preparing: "กำลังเตรียมการอัปโหลด...", compressing: "กำลังบีบอัดรูปภาพ...",
    uploadingFiles: "กำลังอัปโหลดไฟล์...", savingDocuments: "กำลังบันทึกเอกสาร...",
    uploadTypeLabel: "ประเภทเอกสาร", customLabelLabel: "ป้ายกำกับที่กำหนดเอง (ไม่บังคับ)",
    refreshed: "รีเฟรชสำเร็จ", deleteSuccess: "ลบเอกสารแล้ว", uploadSuccess: "อัปโหลดสำเร็จ",
    annotationSaved: "บันทึกคำอธิบายสำเร็จ", annotationFailed: "บันทึกไม่สำเร็จ",
    exportSuccess: "เริ่มส่งออกแล้ว", exportFailed: "ส่งออกไม่สำเร็จ",
    editSuccess: "อัปเดตเอกสารสำเร็จ", editFailed: "ไม่สามารถอัปเดตเอกสารได้",
    deleteFailed: "ไม่สามารถลบเอกสารได้", pleaseSelectDocuments: "กรุณาเลือกเอกสาร",
    downloadFailed: "ไม่สามารถดาวน์โหลดไฟล์ได้",
    noEvidenceTitle: "ยังไม่มีหลักฐานที่อัปโหลด",
    noEvidenceDescription: "อัปโหลดรูปภาพ วิดีโอ และเอกสารตอนนี้ เพื่อให้คุณมีบันทึกพร้อมประทับเวลาหากเกิดข้อพิพาทในภายหลัง",
    upgradeVaultStorage: "อัปเกรดเพื่อจัดเก็บคลังข้อมูลเต็มรูปแบบ",
    addVoiceNote: "เพิ่มบันทึกเสียง", addVideo: "เพิ่มวิดีโอ (ต้องการ Secure)",
    voiceNotesAdded: "บันทึกเสียง", videosAdded: "วิดีโอ",
    upgradeToSecureVideo: "อัปเกรดเป็น Secure สำหรับหลักฐานวิดีโอ",
    upgradeToSecureVideoDesc: "สมาชิก Secure สามารถอัปโหลดวิดีโอเพื่อสร้างหลักฐานที่แข็งแกร่งยิ่งขึ้น",
    upgradeToSecure: "อัปเกรดเป็น Secure", upgradeTitle: "อัปโหลดวิดีโอต้องใช้แผน Secure",
    upgradeDescription: "หลักฐานวิดีโอใช้ได้เฉพาะแผน Secure เท่านั้น อัปเกรดตอนนี้เพื่อปลดล็อก:",
    upgradeBenefitUnlimitedScans: "• สแกนสัญญาเช่าไม่จำกัด",
    upgradeBenefitPriorityQueue: "• การจัดการคดีแบบเร่งด่วน",
    upgradeBenefitVideoEvidence: "• อัปโหลดหลักฐานวิดีโอ",
    upgradeBenefitFullSupport: "• การสนับสนุนอย่างครอบคลุม",
    maybeLater: "ภายหลัง", maxVoiceReached: "สูงสุด 3 บันทึกเสียง", maxVideoReached: "สูงสุด 3 วิดีโอ",
    fileTooLarge: "ไฟล์ใหญ่เกินไป", voiceMaxSize: "บันทึกเสียงต้องน้อยกว่า 5MB",
    videoMaxSize: "วิดีโอต้องน้อยกว่า 80MB", uploadVideo: "อัปโหลดวิดีโอ", recordVideo: "บันทึกวิดีโอ",
    defaultDocLabel: "{docType} - {date}", dear: "เรียน", closingRegards: "ขอแสดงความนับถือ",
    letterExtractionFailed: "[ไม่สามารถดึงเนื้อหาจดหมายได้]", createdBy: "สร้างโดย",
    selectFromDevice: "เลือกจากอุปกรณ์", useCameraToRecord: "ใช้กล้องเพื่อบันทึก",
    imagesOptimizedDesc: "ปรับภาพ {count} รูป ประหยัด {saved}MB",
  },
  zh: {
    back: "返回仪表板", title: "证据库", subtitle: "安全存储您的所有租赁文档",
    uploadFiles: "上传文件", uploadDocument: "上传文档", uploadEvidence: "上传证据",
    documentType: "文档类型", customLabel: "自定义标签", customLabelPlaceholder: "例如，搬入照片",
    selectFiles: "拖放文件到此处或点击浏览", supportedFormats: "PDF、图片（JPG、PNG）、视频（MP4、MOV、AVI）",
    selectedFiles: "选定的文件", uploadButton: "上传", uploading: "上传中...",
    recentUploads: "最近上传", viewTemplates: "查看模板", viewTemplatesDesc: "常见租赁情况的专业信件模板。",
    noDocuments: "暂无文档", noDocumentsDesc: "开始建立您的证据库以获得更好的保护。您上传的所有文档都会安全存储在这里。",
    uploadFirst: "上传第一份文档", deleteConfirm: "您确定吗？",
    confirmDelete: "您确定要删除此信件吗？此操作无法撤消。", confirmBulkDelete: "您确定要删除 {count} 个文件吗？",
    view: "查看", download: "下载", sendEmail: "发送电子邮件", delete: "删除",
    selectAll: "全选", deleteSelected: "删除所选", deleting: "删除中...", selected: "已选",
    storageUsed: "存储：~{used}MB / {limit}MB", filesUsed: "{count} / {limit} 个文件",
    editDocument: "编辑文档", save: "保存", cancel: "取消", saving: "保存中...",
    loadingDocuments: "加载文档中...", exportZip: "导出为ZIP", exportReport: "导出完整报告",
    exporting: "导出中...", bulkActions: "批量操作", annotate: "注释",
    selectFile: "请选择要上传的文件。", uploadFailed: "上传失败。请重试。",
    error: "错误", fileSelected: "个文件已选", filesSelected: "个文件已选",
    preparing: "准备上传...", compressing: "压缩图片...", uploadingFiles: "上传文件...", savingDocuments: "保存文档...",
    uploadTypeLabel: "文档类型", customLabelLabel: "自定义标签（可选）",
    refreshed: "刷新成功", deleteSuccess: "文档已删除", uploadSuccess: "上传成功",
    annotationSaved: "注释已保存", annotationFailed: "保存注释失败",
    exportSuccess: "导出已开始", exportFailed: "导出失败",
    editSuccess: "文档更新成功", editFailed: "更新文档失败",
    deleteFailed: "删除文档失败", pleaseSelectDocuments: "请选择文档", downloadFailed: "下载文件失败",
    noEvidenceTitle: "尚未上传任何证据",
    noEvidenceDescription: "立即上传照片、视频和文件，以便在以后发生争议时拥有带时间戳的记录。",
    upgradeVaultStorage: "升级以获得完整的证据库存储",
    addVoiceNote: "添加语音备忘录", addVideo: "添加视频（需要 Secure）",
    voiceNotesAdded: "语音备忘录", videosAdded: "视频",
    upgradeToSecure: "升级到 Secure", upgradeTitle: "视频上传需要 Secure 计划",
    upgradeDescription: "视频证据仅适用于 Secure 计划。立即升级以解锁：",
    upgradeBenefitUnlimitedScans: "• 无限租约扫描", upgradeBenefitPriorityQueue: "• 优先案件处理",
    upgradeBenefitVideoEvidence: "• 视频证据上传", upgradeBenefitFullSupport: "• 全面支持",
    maybeLater: "稍后再说", maxVoiceReached: "最多 3 个语音备忘录", maxVideoReached: "最多 3 个视频",
    fileTooLarge: "文件过大", voiceMaxSize: "语音备忘录必须小于 5MB", videoMaxSize: "视频必须小于 80MB",
    uploadVideo: "上传视频", recordVideo: "录制视频", defaultDocLabel: "{docType} - {date}",
    dear: "亲爱的", closingRegards: "诚挚的问候", letterExtractionFailed: "[无法提取信件内容]", createdBy: "创建者",
    selectFromDevice: "从设备选择", useCameraToRecord: "使用相机录制",
    imagesOptimizedDesc: "已优化 {count} 张图片，节省 {saved}MB",
  },
  ja: {
    back: "ダッシュボードに戻る", title: "証拠保管庫", subtitle: "すべての賃貸文書を安全に保管",
    uploadFiles: "ファイルをアップロード", uploadDocument: "ドキュメントをアップロード", uploadEvidence: "証拠をアップロード",
    documentType: "ドキュメントタイプ", customLabel: "カスタムラベル", customLabelPlaceholder: "例：入居時の写真",
    selectFiles: "ファイルをドラッグ＆ドロップまたはクリックして参照",
    supportedFormats: "PDF、画像（JPG、PNG）、動画（MP4、MOV、AVI）",
    selectedFiles: "選択したファイル", uploadButton: "アップロード", uploading: "アップロード中...",
    recentUploads: "最近のアップロード", viewTemplates: "テンプレートを表示",
    viewTemplatesDesc: "一般的な賃貸状況のためのプロフェッショナルなレターテンプレート。",
    noDocuments: "まだドキュメントがありません",
    noDocumentsDesc: "より良い保護のために証拠保管庫の構築を開始してください。アップロードしたすべてのドキュメントはここに安全に保存されます。",
    uploadFirst: "最初のドキュメントをアップロード", deleteConfirm: "よろしいですか？",
    confirmDelete: "このレターを削除してもよろしいですか？この操作は元に戻せません。",
    confirmBulkDelete: "{count}個のファイルを削除してもよろしいですか？",
    view: "表示", download: "ダウンロード", sendEmail: "メールを送信", delete: "削除",
    selectAll: "すべて選択", deleteSelected: "選択項目を削除", deleting: "削除中...", selected: "選択済み",
    storageUsed: "ストレージ：~{used}MB / {limit}MB", filesUsed: "{count} / {limit} ファイル",
    editDocument: "ドキュメントを編集", save: "保存", cancel: "キャンセル", saving: "保存中...",
    loadingDocuments: "ドキュメント読み込み中...", exportZip: "ZIPとしてエクスポート", exportReport: "完全なレポートをエクスポート",
    exporting: "エクスポート中...", bulkActions: "一括操作", annotate: "注釈",
    selectFile: "アップロードするファイルを選択してください。", uploadFailed: "アップロードに失敗しました。もう一度お試しください。",
    error: "エラー", fileSelected: "個のファイルを選択", filesSelected: "個のファイルを選択",
    preparing: "アップロード準備中...", compressing: "画像を圧縮中...",
    uploadingFiles: "ファイルをアップロード中...", savingDocuments: "ドキュメントを保存中...",
    uploadTypeLabel: "ドキュメントタイプ", customLabelLabel: "カスタムラベル（オプション）",
    refreshed: "更新成功", deleteSuccess: "ドキュメントを削除しました", uploadSuccess: "アップロード成功",
    annotationSaved: "注釈を保存しました", annotationFailed: "注釈の保存に失敗しました",
    exportSuccess: "エクスポート開始", exportFailed: "エクスポート失敗",
    editSuccess: "ドキュメントを正常に更新しました", editFailed: "ドキュメントの更新に失敗しました",
    deleteFailed: "ドキュメントの削除に失敗しました", pleaseSelectDocuments: "ドキュメントを選択してください",
    downloadFailed: "ファイルのダウンロードに失敗しました",
    noEvidenceTitle: "まだ証拠がアップロードされていません",
    noEvidenceDescription: "紛争が発生した場合にタイムスタンプ付きの記録を残すため、写真、ビデオ、ドキュメントを今すぐアップロードしてください。",
    upgradeVaultStorage: "完全な保管庫ストレージにアップグレード",
    addVoiceNote: "音声メモを追加", addVideo: "動画を追加（Secureが必要）",
    voiceNotesAdded: "音声メモ", videosAdded: "動画",
    upgradeToSecure: "Secureにアップグレード", upgradeTitle: "動画アップロードにはSecureが必要",
    upgradeDescription: "動画証拠はSecureプランでのみ利用可能です。今すぐアップグレードしてロック解除：",
    upgradeBenefitUnlimitedScans: "• 無制限の賃貸契約スキャン", upgradeBenefitPriorityQueue: "• 優先的なケース処理",
    upgradeBenefitVideoEvidence: "• 動画証拠のアップロード", upgradeBenefitFullSupport: "• 包括的なサポート",
    maybeLater: "後で", maxVoiceReached: "最大3件の音声メモ", maxVideoReached: "最大3件の動画",
    fileTooLarge: "ファイルが大きすぎます", voiceMaxSize: "音声メモは5MB未満である必要があります",
    videoMaxSize: "動画は80MB未満である必要があります", uploadVideo: "動画をアップロード", recordVideo: "動画を録画",
    defaultDocLabel: "{docType} - {date}", dear: "拝啓", closingRegards: "敬具",
    letterExtractionFailed: "[手紙の内容を抽出できませんでした]", createdBy: "作成者",
    selectFromDevice: "デバイスから選択", useCameraToRecord: "カメラで録画",
    imagesOptimizedDesc: "{count}枚の画像を最適化、{saved}MB削減",
  },
  ko: {
    back: "대시보드로 돌아가기", title: "증거 보관소", subtitle: "모든 임대 문서를 안전하게 보관",
    uploadFiles: "파일 업로드", uploadDocument: "문서 업로드", uploadEvidence: "증거 업로드",
    documentType: "문서 유형", customLabel: "사용자 지정 레이블", customLabelPlaceholder: "예: 입주 사진",
    selectFiles: "여기에 파일을 드래그하거나 클릭하여 찾아보기",
    supportedFormats: "PDF, 이미지 (JPG, PNG), 비디오 (MP4, MOV, AVI)",
    selectedFiles: "선택된 파일", uploadButton: "업로드", uploading: "업로드 중...",
    recentUploads: "최근 업로드", viewTemplates: "템플릿 보기",
    viewTemplatesDesc: "일반적인 임대 상황을 위한 전문 편지 템플릿.",
    noDocuments: "아직 문서 없음",
    noDocumentsDesc: "더 나은 보호를 위해 증거 보관소 구축을 시작하세요. 업로드한 모든 문서는 여기에 안전하게 저장됩니다.",
    uploadFirst: "첫 번째 문서 업로드", deleteConfirm: "확실합니까?",
    confirmDelete: "이 편지를 삭제하시겠습니까? 이 작업은 취소할 수 없습니다.",
    confirmBulkDelete: "{count}개의 파일을 삭제하시겠습니까?",
    view: "보기", download: "다운로드", sendEmail: "이메일 보내기", delete: "삭제",
    selectAll: "모두 선택", deleteSelected: "선택 항목 삭제", deleting: "삭제 중...", selected: "선택됨",
    storageUsed: "저장소: ~{used}MB / {limit}MB", filesUsed: "{count} / {limit} 파일",
    editDocument: "문서 편집", save: "저장", cancel: "취소", saving: "저장 중...",
    loadingDocuments: "문서 로딩 중...", exportZip: "ZIP으로 내보내기", exportReport: "전체 보고서 내보내기",
    exporting: "내보내기 중...", bulkActions: "일괄 작업", annotate: "주석",
    selectFile: "업로드할 파일을 선택하세요.", uploadFailed: "업로드 실패. 다시 시도해주세요.",
    error: "오류", fileSelected: "개 파일 선택됨", filesSelected: "개 파일 선택됨",
    preparing: "업로드 준비 중...", compressing: "이미지 압축 중...",
    uploadingFiles: "파일 업로드 중...", savingDocuments: "문서 저장 중...",
    uploadTypeLabel: "문서 유형", customLabelLabel: "사용자 지정 레이블 (선택사항)",
    refreshed: "새로고침 성공", deleteSuccess: "문서 삭제됨", uploadSuccess: "업로드 성공",
    annotationSaved: "주석 저장됨", annotationFailed: "주석 저장 실패",
    exportSuccess: "내보내기 시작됨", exportFailed: "내보내기 실패",
    editSuccess: "문서 업데이트 성공", editFailed: "문서 업데이트 실패",
    deleteFailed: "문서 삭제 실패", pleaseSelectDocuments: "문서를 선택하세요",
    downloadFailed: "파일 다운로드 실패",
    noEvidenceTitle: "아직 증거가 업로드되지 않았습니다.",
    noEvidenceDescription: "분쟁 발생 시 타임스탬프가 찍힌 기록을 가질 수 있도록 지금 사진, 동영상 및 문서를 업로드하세요.",
    upgradeVaultStorage: "전체 볼트 저장 공간을 위해 업그레이드",
    addVoiceNote: "음성 메모 추가", addVideo: "동영상 추가（Secure 필요）",
    voiceNotesAdded: "음성 메모", videosAdded: "동영상",
    upgradeToSecure: "Secure로 업그레이드", upgradeTitle: "동영상 업로드에는 Secure 필요",
    upgradeDescription: "동영상 증거는 Secure 플랜에서만 사용할 수 있습니다. 지금 업그레이드하여 잠금 해제:",
    upgradeBenefitUnlimitedScans: "• 무제한 임대 계약 스캔", upgradeBenefitPriorityQueue: "• 우선 사례 처리",
    upgradeBenefitVideoEvidence: "• 동영상 증거 업로드", upgradeBenefitFullSupport: "• 포괄적인 지원",
    maybeLater: "나중에", maxVoiceReached: "최대 3개의 음성 메모", maxVideoReached: "최대 3개의 동영상",
    fileTooLarge: "파일이 너무 큼", voiceMaxSize: "음성 메모는 5MB 미만이어야 합니다",
    videoMaxSize: "동영상은 80MB 미만이어야 합니다", uploadVideo: "동영상 업로드", recordVideo: "동영상 녹화",
    defaultDocLabel: "{docType} - {date}", dear: "에게", closingRegards: "안부를 전하며",
    letterExtractionFailed: "[편지 내용을 추출할 수 없습니다]", createdBy: "작성자",
    selectFromDevice: "기기에서 선택", useCameraToRecord: "카메라로 녹화",
    imagesOptimizedDesc: "{count}개 이미지 최적화, {saved}MB 절약",
  },
  ru: {
    back: "Назад к панели", title: "Хранилище доказательств", subtitle: "Безопасное хранение всей арендной документации",
    uploadFiles: "Загрузить файлы", uploadDocument: "Загрузить документ", uploadEvidence: "Загрузить доказательства",
    documentType: "Тип документа", customLabel: "Произвольная метка", customLabelPlaceholder: "напр., Фото при въезде",
    selectFiles: "Перетащите файлы сюда или нажмите для выбора",
    supportedFormats: "PDF, Изображения (JPG, PNG), Видео (MP4, MOV, AVI)",
    selectedFiles: "Выбранные файлы", uploadButton: "Загрузить", uploading: "Загрузка...",
    recentUploads: "Недавние загрузки", viewTemplates: "Посмотреть шаблоны",
    viewTemplatesDesc: "Профессиональные шаблоны писем для типичных арендных ситуаций.",
    noDocuments: "Документов пока нет",
    noDocumentsDesc: "Начните создавать хранилище доказательств для лучшей защиты. Все загруженные документы безопасно хранятся здесь.",
    uploadFirst: "Загрузить первый документ", deleteConfirm: "Вы уверены?",
    confirmDelete: "Вы уверены, что хотите удалить это письмо? Это действие необратимо.",
    confirmBulkDelete: "Вы уверены, что хотите удалить файлов: {count}?",
    view: "Посмотреть", download: "Скачать", sendEmail: "Отправить по почте", delete: "Удалить",
    selectAll: "Выбрать все", deleteSelected: "Удалить выбранные", deleting: "Удаление...", selected: "выбрано",
    storageUsed: "Хранилище: ~{used}МБ / {limit}МБ", filesUsed: "{count} / {limit} файлов",
    editDocument: "Редактировать документ", save: "Сохранить", cancel: "Отмена", saving: "Сохранение...",
    loadingDocuments: "Загрузка документов...", exportZip: "Экспорт в ZIP", exportReport: "Экспортировать полный отчёт",
    exporting: "Экспорт...", bulkActions: "Массовые действия", annotate: "Аннотировать",
    selectFile: "Пожалуйста, выберите файлы для загрузки.", uploadFailed: "Загрузка не удалась. Попробуйте снова.",
    error: "Ошибка", fileSelected: "файл выбран", filesSelected: "файлов выбрано",
    preparing: "Подготовка загрузки...", compressing: "Сжатие изображений...",
    uploadingFiles: "Загрузка файлов...", savingDocuments: "Сохранение документов...",
    uploadTypeLabel: "Тип документа", customLabelLabel: "Произвольная метка (необязательно)",
    refreshed: "Обновлено успешно", deleteSuccess: "Документ удалён", uploadSuccess: "Загрузка успешна",
    annotationSaved: "Аннотация сохранена", annotationFailed: "Не удалось сохранить аннотацию",
    exportSuccess: "Экспорт начат", exportFailed: "Экспорт не удался",
    editSuccess: "Документ успешно обновлён", editFailed: "Не удалось обновить документ",
    deleteFailed: "Не удалось удалить документ", pleaseSelectDocuments: "Пожалуйста, выберите документы",
    downloadFailed: "Не удалось скачать файл",
    noEvidenceTitle: "Доказательства еще не загружены",
    noEvidenceDescription: "Загрузите фотографии, видео и документы сейчас, чтобы иметь запись с отметками времени в случае спора позже.",
    upgradeVaultStorage: "Обновите для полного хранилища",
    addVoiceNote: "Добавить голосовую заметку", addVideo: "Добавить видео (требуется Secure)",
    voiceNotesAdded: "голосовых заметок", videosAdded: "видео",
    upgradeToSecure: "Обновить до Secure", upgradeTitle: "Для загрузки видео требуется Secure",
    upgradeDescription: "Видеодоказательства доступны только в плане Secure. Обновитесь сейчас, чтобы разблокировать:",
    upgradeBenefitUnlimitedScans: "• Неограниченные сканы договоров аренды",
    upgradeBenefitPriorityQueue: "• Приоритетная обработка дел",
    upgradeBenefitVideoEvidence: "• Загрузка видеодоказательств",
    upgradeBenefitFullSupport: "• Полная поддержка",
    maybeLater: "Позже", maxVoiceReached: "Максимум 3 голосовые заметки", maxVideoReached: "Максимум 3 видео",
    fileTooLarge: "Файл слишком большой", voiceMaxSize: "Голосовые заметки должны быть менее 5 МБ",
    videoMaxSize: "Видео должны быть менее 80 МБ", uploadVideo: "Загрузить видео", recordVideo: "Записать видео",
    defaultDocLabel: "{docType} - {date}", dear: "Уважаемый", closingRegards: "С уважением",
    letterExtractionFailed: "[Не удалось извлечь содержимое письма]", createdBy: "Создано",
    selectFromDevice: "Выбрать с устройства", useCameraToRecord: "Записать с помощью камеры",
    imagesOptimizedDesc: "Оптимизировано {count} изображений, сэкономлено {saved}МБ",
  }
};

const fallbackStrings = stringsAll.en;

export function getEvidenceStrings(language) {
  return stringsAll[language] || fallbackStrings;
}