const folderStrings = {
  en: {
    newFolder: "New Folder",
    createFolder: "Create Folder",
    renameFolder: "Rename Folder",
    deleteFolder: "Delete Folder",
    moveToFolder: "Move to Folder",
    allFiles: "All Files",
    rootNoFolder: "Uploads",
    folderName: "Folder Name",
    folderNamePlaceholder: "e.g., Move-in Photos, Receipts, Letters",
    create: "Create",
    rename: "Rename",
    cancel: "Cancel",
    folderCreated: "Folder created",
    folderRenamed: "Folder renamed",
    folderDeleted: "Folder deleted",
    fileMoved: "File moved",
    folderNameEmpty: "Folder name cannot be empty",
    deleteConfirm: "Delete this folder?",
    deleteWarning: "files will be moved to root level (not deleted).",
    deleteFolderBtn: "Delete Folder",
    move: "Move",
    noFolders: "No folders yet",
    createFirstFolder: "Create folders to organize your evidence",
    emptyFolder: "This folder is empty",
    unsorted: "Unsorted Files",
    saveToFolder: "Save to Folder",
    createNewFolder: "+ Create New Folder",
    newFolderName: "New folder name",
    savingTo: "Saving to:",
    rootLevel: "Uploads",
  },
  th: {
    newFolder: "โฟลเดอร์ใหม่",
    createFolder: "สร้างโฟลเดอร์",
    renameFolder: "เปลี่ยนชื่อโฟลเดอร์",
    deleteFolder: "ลบโฟลเดอร์",
    moveToFolder: "ย้ายไปยังโฟลเดอร์",
    allFiles: "ไฟล์ทั้งหมด",
    rootNoFolder: "อัปโหลด",
    folderName: "ชื่อโฟลเดอร์",
    folderNamePlaceholder: "เช่น รูปตอนย้ายเข้า, ใบเสร็จ, จดหมาย",
    create: "สร้าง",
    rename: "เปลี่ยนชื่อ",
    cancel: "ยกเลิก",
    folderCreated: "สร้างโฟลเดอร์แล้ว",
    folderRenamed: "เปลี่ยนชื่อโฟลเดอร์แล้ว",
    folderDeleted: "ลบโฟลเดอร์แล้ว",
    fileMoved: "ย้ายไฟล์แล้ว",
    folderNameEmpty: "ชื่อโฟลเดอร์ไม่สามารถว่างได้",
    deleteConfirm: "ลบโฟลเดอร์นี้?",
    deleteWarning: "ไฟล์จะถูกย้ายไปยังรูท (ไม่ถูกลบ)",
    deleteFolderBtn: "ลบโฟลเดอร์",
    move: "ย้าย",
    noFolders: "ยังไม่มีโฟลเดอร์",
    createFirstFolder: "สร้างโฟลเดอร์เพื่อจัดระเบียบหลักฐาน",
    emptyFolder: "โฟลเดอร์นี้ว่างเปล่า",
    unsorted: "ไฟล์ที่ไม่ได้จัดหมวด",
    saveToFolder: "บันทึกไปยังโฟลเดอร์",
    createNewFolder: "+ สร้างโฟลเดอร์ใหม่",
    newFolderName: "ชื่อโฟลเดอร์ใหม่",
    savingTo: "บันทึกไปยัง:",
    rootLevel: "อัปโหลด",
  },
  zh: {
    newFolder: "新文件夹", createFolder: "创建文件夹", renameFolder: "重命名文件夹",
    deleteFolder: "删除文件夹", moveToFolder: "移动到文件夹", allFiles: "所有文件",
    rootNoFolder: "上传", folderName: "文件夹名称",
    folderNamePlaceholder: "例如：搬入照片、收据、信件",
    create: "创建", rename: "重命名", cancel: "取消",
    folderCreated: "文件夹已创建", folderRenamed: "文件夹已重命名",
    folderDeleted: "文件夹已删除", fileMoved: "文件已移动",
    folderNameEmpty: "文件夹名称不能为空", deleteConfirm: "删除此文件夹？",
    deleteWarning: "文件将移至根目录（不会被删除）。",
    deleteFolderBtn: "删除文件夹", move: "移动", noFolders: "暂无文件夹",
    createFirstFolder: "创建文件夹来整理您的证据", emptyFolder: "此文件夹为空",
    unsorted: "未分类文件",
    saveToFolder: "保存到文件夹", createNewFolder: "+ 新建文件夹",
    newFolderName: "新文件夹名称", savingTo: "保存到：", rootLevel: "根目录（所有文件）",
  },
  ja: {
    newFolder: "新しいフォルダ", createFolder: "フォルダを作成", renameFolder: "フォルダの名前を変更",
    deleteFolder: "フォルダを削除", moveToFolder: "フォルダに移動", allFiles: "すべてのファイル",
    rootNoFolder: "アップロード", folderName: "フォルダ名",
    folderNamePlaceholder: "例：入居写真、領収書、レター",
    create: "作成", rename: "名前変更", cancel: "キャンセル",
    folderCreated: "フォルダを作成しました", folderRenamed: "フォルダの名前を変更しました",
    folderDeleted: "フォルダを削除しました", fileMoved: "ファイルを移動しました",
    folderNameEmpty: "フォルダ名は空にできません", deleteConfirm: "このフォルダを削除しますか？",
    deleteWarning: "ファイルはルートレベルに移動されます（削除されません）。",
    deleteFolderBtn: "フォルダを削除", move: "移動", noFolders: "フォルダはまだありません",
    createFirstFolder: "証拠を整理するフォルダを作成しましょう", emptyFolder: "このフォルダは空です",
    unsorted: "未整理ファイル",
    saveToFolder: "フォルダに保存", createNewFolder: "+ 新しいフォルダを作成",
    newFolderName: "新しいフォルダ名", savingTo: "保存先：", rootLevel: "ルート（すべてのファイル）",
  },
  ko: {
    newFolder: "새 폴더", createFolder: "폴더 만들기", renameFolder: "폴더 이름 변경",
    deleteFolder: "폴더 삭제", moveToFolder: "폴더로 이동", allFiles: "모든 파일",
    rootNoFolder: "업로드", folderName: "폴더 이름",
    folderNamePlaceholder: "예: 입주 사진, 영수증, 편지",
    create: "만들기", rename: "이름 변경", cancel: "취소",
    folderCreated: "폴더가 생성되었습니다", folderRenamed: "폴더 이름이 변경되었습니다",
    folderDeleted: "폴더가 삭제되었습니다", fileMoved: "파일이 이동되었습니다",
    folderNameEmpty: "폴더 이름은 비워둘 수 없습니다", deleteConfirm: "이 폴더를 삭제하시겠습니까?",
    deleteWarning: "파일은 루트 레벨로 이동됩니다 (삭제되지 않음).",
    deleteFolderBtn: "폴더 삭제", move: "이동", noFolders: "아직 폴더가 없습니다",
    createFirstFolder: "증거를 정리할 폴더를 만드세요", emptyFolder: "이 폴더는 비어 있습니다",
    unsorted: "미분류 파일",
    saveToFolder: "폴더에 저장", createNewFolder: "+ 새 폴더 만들기",
    newFolderName: "새 폴더 이름", savingTo: "저장 위치:", rootLevel: "루트 (모든 파일)",
  },
  ru: {
    newFolder: "Новая папка", createFolder: "Создать папку", renameFolder: "Переименовать папку",
    deleteFolder: "Удалить папку", moveToFolder: "Переместить в папку", allFiles: "Все файлы",
    rootNoFolder: "Загрузки", folderName: "Имя папки",
    folderNamePlaceholder: "напр., Фото при въезде, Чеки, Письма",
    create: "Создать", rename: "Переименовать", cancel: "Отмена",
    folderCreated: "Папка создана", folderRenamed: "Папка переименована",
    folderDeleted: "Папка удалена", fileMoved: "Файл перемещён",
    folderNameEmpty: "Имя папки не может быть пустым", deleteConfirm: "Удалить эту папку?",
    deleteWarning: "файлов будут перемещены в корень (не удалены).",
    deleteFolderBtn: "Удалить папку", move: "Переместить", noFolders: "Папок пока нет",
    createFirstFolder: "Создайте папки для организации ваших доказательств", emptyFolder: "Эта папка пуста",
    unsorted: "Несортированные файлы",
    saveToFolder: "Сохранить в папку", createNewFolder: "+ Создать новую папку",
    newFolderName: "Имя новой папки", savingTo: "Сохранить в:", rootLevel: "Загрузки",
  }
};

export function getFolderStrings(language) {
  return folderStrings[language] || folderStrings.en;
}