
import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Download, Shield, FileText, ArrowLeft, AlertTriangle, Info, CheckCircle2, AlertCircle, Sparkles, Loader2, Crown, Lock } from "lucide-react";
import { FeatureGate } from "../components/shared/FeatureGate";

export default function ReportFull() {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const urlParams = new URLSearchParams(window.location.search);
  const scanId = urlParams.get('scanId');
  
  const [generatingLetters, setGeneratingLetters] = useState(false);
  const [generationResult, setGenerationResult] = useState(null);

  const { data: user } = useQuery({
    queryKey: ['currentUser'],
    queryFn: () => base44.auth.me(),
  });

  const { data: scan } = useQuery({
    queryKey: ['scan', scanId],
    queryFn: async () => {
      const scans = await base44.entities.LeaseScan.list();
      return scans.find(s => s.id === scanId);
    },
    enabled: !!scanId,
  });

  const { data: lease } = useQuery({
    queryKey: ['lease', scan?.lease_id],
    queryFn: async () => {
      const leases = await base44.entities.Lease.list();
      return leases.find(l => l.id === scan.lease_id);
    },
    enabled: !!scan?.lease_id,
  });

  const language = user?.language || 'en';
  const isDarkMode = user?.theme === 'dark';
  const isSecureTier = user?.plan_tier === 'secure';
  const userTier = user?.plan_tier || 'free';

  const colors = isDarkMode ? {
    bg: '#1A1D1F',
    cardBg: '#2A2D30',
    textPrimary: '#ECEFED',
    textSecondary: '#A8ABAD',
    borderColor: '#3A3D40'
  } : {
    bg: '#F8FAFC',
    cardBg: '#FFFFFF',
    textPrimary: '#1A1D1F',
    textSecondary: '#64748b',
    borderColor: '#E5E7EB'
  };

  const t = {
    en: {
      autoGenerateLetters: "Auto-Generate Letters",
      autoGenerateDesc: "AI creates negotiation letters based on Lease Shield scan recommendations",
      secureTierOnly: "Secure Tier Only",
      generating: "Analyzing scan & generating...",
      generated: "Letters Generated!",
      viewLetters: "View Letters",
      upgradeToSecure: "Upgrade to Secure",
      upgradeDesc: "Get AI letter generation based on your lease scan findings",
      lettersGenerated: "letters generated successfully",
      analysisComplete: "Analysis complete - letters created from scan recommendations",
      noScanReportFound: "No scan report found",
      uploadALease: "Upload a Lease",
      fullLeaseReport: "Full Lease Report",
      downloadPDF: "Download PDF",
      riskAssessment: "Risk Assessment",
      score: "Score",
      keyLeaseTerms: "Key Lease Terms",
      propertyAddress: "Property Address",
      monthlyRent: "Monthly Rent",
      securityDeposit: "Security Deposit",
      leasePeriod: "Lease Period",
      leaseType: "Lease Type",
      language: "Language",
      detailedIssues: "Detailed Issues & Recommendations",
      evidence: "Evidence",
      explanation: "Explanation",
      recommendation: "Recommendation",
      impact: "Impact",
      likelihood: "Likelihood",
      missingProtections: "Missing Protections",
      suggestedNextSteps: "Suggested Next Steps",
      enableDepositShield: "Enable Deposit Shield",
      trackYourSecurityDeposit: "Track your security deposit",
      generateLetter: "Generate Letter",
      professionalTenantLetters: "Professional tenant letters",
      failedToGenerateLetters: "Failed to generate letters. Please try again."
    },
    th: {
      autoGenerateLetters: "สร้างจดหมายอัตโนมัติ",
      autoGenerateDesc: "AI สร้างจดหมายเจรจาตามคำแนะนำจากการสแกนของ Lease Shield",
      secureTierOnly: "สำหรับ Secure เท่านั้น",
      generating: "กำลังวิเคราะห์และสร้าง...",
      generated: "สร้างจดหมายเรียบร้อย!",
      viewLetters: "ดูจดหมาย",
      upgradeToSecure: "อัปเกรดเป็น Secure",
      upgradeDesc: "รับการสร้างจดหมาย AI ตามผลการสแกนสัญญาเช่าของคุณ",
      lettersGenerated: "สร้างจดหมายสำเร็จแล้ว",
      analysisComplete: "วิเคราะห์เสร็จสิ้น - สร้างจดหมายจากคำแนะนำของการสแกน",
      noScanReportFound: "ไม่พบรายงานการสแกน",
      uploadALease: "อัปโหลดสัญญาเช่า",
      fullLeaseReport: "รายงานการเช่าฉบับเต็ม",
      downloadPDF: "ดาวน์โหลด PDF",
      riskAssessment: "การประเมินความเสี่ยง",
      score: "คะแนน",
      keyLeaseTerms: "ข้อกำหนดสัญญาเช่าที่สำคัญ",
      propertyAddress: "ที่อยู่ทรัพย์สิน",
      monthlyRent: "ค่าเช่ารายเดือน",
      securityDeposit: "เงินประกัน",
      leasePeriod: "ระยะเวลาเช่า",
      leaseType: "ประเภทสัญญาเช่า",
      language: "ภาษา",
      detailedIssues: "ปัญหาและข้อแนะนำโดยละเอียด",
      evidence: "หลักฐาน",
      explanation: "คำอธิบาย",
      recommendation: "ข้อแนะนำ",
      impact: "ผลกระทบ",
      likelihood: "โอกาส",
      missingProtections: "การป้องกันที่ขาดหายไป",
      suggestedNextSteps: "ขั้นตอนที่แนะนำ",
      enableDepositShield: "เปิดใช้งาน Deposit Shield",
      trackYourSecurityDeposit: "ติดตามเงินมัดจำของคุณ",
      generateLetter: "สร้างจดหมาย",
      professionalTenantLetters: "จดหมายสำหรับผู้เช่ามืออาชีพ",
      failedToGenerateLetters: "ไม่สามารถสร้างจดหมายได้ กรุณาลองอีกครั้ง"
    }
  };

  const strings = t[language];

  // Analyze scan to determine which letters to generate
  const analyzeAndGenerateLetters = async () => {
    if (!scan || !lease) return;

    setGeneratingLetters(true);
    setGenerationResult(null);

    try {
      const lettersToGenerate = [];
      const fullFlags = scan.scan_full?.flags || [];

      // NEW: Generate pre-signing negotiation letter if there are any flags
      if (fullFlags.length > 0) {
        // Build concerns list from flags
        const concerns = fullFlags
          .slice(0, 5) // Take top 5 issues
          .map((flag, idx) => {
            const num = idx + 1;
            return `${num}. ${flag.title || flag.category}: ${flag.explanation || flag.description || ''}`;
          })
          .join('\n');

        lettersToGenerate.push({
          subject: 'lease_negotiation',
          params: {
            concerns_list: concerns
          }
        });
      }

      // Check for deposit-related issues (post-signing)
      const hasDepositIssues = fullFlags.some(f => 
        f.category?.toLowerCase().includes('deposit') || 
        f.title?.toLowerCase().includes('deposit')
      );
      if (hasDepositIssues) {
        lettersToGenerate.push({ subject: 'deposit', params: {} });
      }

      // Check for damage/deduction issues
      const hasDamageIssues = fullFlags.some(f => 
        f.category?.toLowerCase().includes('damage') ||
        f.category?.toLowerCase().includes('deduction') ||
        f.title?.toLowerCase().includes('damage')
      );
      if (hasDamageIssues) {
        lettersToGenerate.push({ subject: 'deductions', params: {} });
      }

      // Check for termination issues
      const hasTerminationIssues = fullFlags.some(f => 
        f.category?.toLowerCase().includes('termination') ||
        f.category?.toLowerCase().includes('notice') ||
        f.title?.toLowerCase().includes('termination')
      );
      if (hasTerminationIssues) {
        lettersToGenerate.push({ subject: 'early_termination', params: {} });
      }

      // Create a case if one doesn't exist
      const existingCases = await base44.entities.Case.filter({ lease_id: lease.id });
      let caseId;

      if (existingCases && existingCases.length > 0) {
        caseId = existingCases[0].id;
      } else {
        // Create new case
        const newCase = await base44.entities.Case.create({
          user_email: user.email,
          lease_id: lease.id,
          type: 'deposit',
          status: 'ready_drafts',
          dispute_amount: lease.deposit_amount || 0,
          summary: `Auto-generated from lease scan - Risk Score: ${scan.risk_score}/100`,
          landlord_name: user.landlord_name || '',
          timeline: [{
            timestamp: new Date().toISOString(),
            event: 'case_created_from_scan',
            actor: user.email,
            meta: { scan_id: scanId, auto_generated: true }
          }]
        });
        caseId = newCase.id;
      }

      // Generate each recommended letter
      const results = [];
      for (const letterConfig of lettersToGenerate) {
        try {
          const response = await base44.functions.invoke('generatePhase1Letter', {
            caseId: caseId,
            subject: letterConfig.subject,
            tenant_name: user.full_name,
            landlord_name: user.landlord_name || 'Landlord',
            property_address: lease.property_address || '',
            deposit_amount: lease.deposit_amount || 0,
            contract_ref: lease.start_date 
              ? `Lease dated ${new Date(lease.start_date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}` 
              : 'Lease Agreement',
            ...letterConfig.params
          });

          if (response.data?.ok) {
            results.push({
              subject: letterConfig.subject,
              success: true,
              urls: response.data.urls
            });
          }
        } catch (error) {
          console.error(`Failed to generate ${letterConfig.subject} letter:`, error);
          results.push({
            subject: letterConfig.subject,
            success: false,
            error: error.message
          });
        }
      }

      setGenerationResult({
        caseId,
        letters: results,
        totalGenerated: results.filter(r => r.success).length
      });

      // Refresh case data
      queryClient.invalidateQueries({ queryKey: ['case', caseId] });

    } catch (error) {
      console.error('Letter generation failed:', error);
      alert(strings.failedToGenerateLetters);
    } finally {
      setGeneratingLetters(false);
    }
  };

  if (!scan || !lease) {
    return (
      <div className="min-h-screen flex items-center justify-center p-6" style={{ backgroundColor: colors.bg }}>
        <div className="text-center">
          <FileText className="w-16 h-16 mx-auto mb-4" style={{ color: colors.textSecondary, opacity: 0.3 }} />
          <p style={{ color: colors.textSecondary }} className="mb-4">
            {strings.noScanReportFound}
          </p>
          <Button onClick={() => navigate(createPageUrl("UploadScan"))}>
            {strings.uploadALease}
          </Button>
        </div>
      </div>
    );
  }

  const getSeverityIcon = (severity) => {
    const icons = { critical: AlertTriangle, high: AlertTriangle, medium: Info, low: CheckCircle2 };
    return icons[severity] || Info;
  };

  const getSeverityColor = (severity) => {
    const colors = {
      critical: "text-red-600 bg-red-50 border-red-200",
      high: "text-orange-600 bg-orange-50 border-orange-200",
      medium: "text-amber-600 bg-amber-50 border-amber-200",
      low: "text-blue-600 bg-blue-50 border-blue-200"
    };
    return colors[severity] || "text-slate-600 bg-slate-50 border-slate-200";
  };

  // LIMIT FLAGS BASED ON TIER (consistent with ScanPreview)
  const getFullDisplayFlags = () => {
    const allFlags = scan.scan_full?.flags || [];
    
    // Lite tier: Show max 5 flags
    if (userTier === 'lite') {
      return allFlags.slice(0, 5);
    }
    
    // Free tier shouldn't access this page, but if they do, show 4
    if (userTier === 'free') {
      return allFlags.slice(0, 4);
    }
    
    // Protect and Secure: Show all flags
    return allFlags;
  };

  const fullFlags = getFullDisplayFlags();
  const totalFlags = scan.scan_full?.flags?.length || 0;
  const hiddenFlagsCount = totalFlags - fullFlags.length;
  const missingItems = scan.scan_full?.missing_items || [];
  const keyTerms = scan.scan_full?.key_terms || {};

  return (
    <FeatureGate feature="full_report">
      <div className="min-h-screen p-4 md:p-6" style={{ backgroundColor: colors.bg }}>
        <div className="max-w-4xl mx-auto">
          <div className="flex items-center gap-4 mb-6">
            <Button
              variant="outline"
              size="icon"
              onClick={() => navigate(createPageUrl("Dashboard"))}
            >
              <ArrowLeft className="w-5 h-5" />
            </Button>
            <div className="flex-1">
              <h1 className="text-2xl md:text-3xl font-bold" style={{ color: colors.textPrimary }}>
                {strings.fullLeaseReport}
              </h1>
              <p style={{ color: colors.textSecondary }}>{lease.property_address || 'Lease Agreement'}</p>
            </div>
            <Button className="bg-blue-600 hover:bg-blue-700">
              <Download className="w-4 h-4 mr-2" />
              {strings.downloadPDF}
            </Button>
          </div>

          {/* Risk Score Summary */}
          <Card className="mb-6 border-none shadow-lg" style={{ backgroundColor: colors.cardBg }}>
            <CardHeader className="bg-gradient-to-r from-blue-600 to-blue-800 text-white">
              <CardTitle className="flex items-center justify-between">
                <span>{strings.riskAssessment}</span>
                <Badge className="bg-white text-blue-800 text-lg px-4 py-2">
                  {strings.score}: {scan.risk_score}/100
                </Badge>
              </CardTitle>
            </CardHeader>
            <CardContent className="p-6">
              <p className="leading-relaxed" style={{ color: colors.textPrimary }}>{scan.summary}</p>
            </CardContent>
          </Card>

          {/* Key Terms */}
          {Object.keys(keyTerms).length > 0 && (
            <Card className="mb-6 border-none shadow-lg" style={{ backgroundColor: colors.cardBg }}>
              <CardHeader className="border-b" style={{ borderColor: colors.borderColor }}>
                <CardTitle className="flex items-center gap-2" style={{ color: colors.textPrimary }}>
                  <FileText className="w-5 h-5 text-blue-600" />
                  {strings.keyLeaseTerms}
                </CardTitle>
              </CardHeader>
              <CardContent className="p-6">
                <div className="grid md:grid-cols-2 gap-4">
                  {keyTerms.property_address && (
                    <div className="p-4 rounded-lg" style={{ backgroundColor: isDarkMode ? '#1F2937' : '#F8FAFC' }}>
                      <p className="text-xs font-semibold mb-1" style={{ color: colors.textSecondary }}>{strings.propertyAddress}</p>
                      <p className="font-medium" style={{ color: colors.textPrimary }}>{keyTerms.property_address}</p>
                    </div>
                  )}
                  {keyTerms.rent_amount && (
                    <div className="p-4 rounded-lg" style={{ backgroundColor: isDarkMode ? '#1F2937' : '#F8FAFC' }}>
                      <p className="text-xs font-semibold mb-1" style={{ color: colors.textSecondary }}>{strings.monthlyRent}</p>
                      <p className="font-medium" style={{ color: colors.textPrimary }}>฿{keyTerms.rent_amount.toLocaleString()}</p>
                    </div>
                  )}
                  {keyTerms.deposit_amount && (
                    <div className="p-4 rounded-lg" style={{ backgroundColor: isDarkMode ? '#1F2937' : '#F8FAFC' }}>
                      <p className="text-xs font-semibold mb-1" style={{ color: colors.textSecondary }}>{strings.securityDeposit}</p>
                      <p className="font-medium" style={{ color: colors.textPrimary }}>฿{keyTerms.deposit_amount.toLocaleString()}</p>
                    </div>
                  )}
                  {keyTerms.start_date && (
                    <div className="p-4 rounded-lg" style={{ backgroundColor: isDarkMode ? '#1F2937' : '#F8FAFC' }}>
                      <p className="text-xs font-semibold mb-1" style={{ color: colors.textSecondary }}>{strings.leasePeriod}</p>
                      <p className="font-medium" style={{ color: colors.textPrimary }}>
                        {keyTerms.start_date} {keyTerms.end_date && `to ${keyTerms.end_date}`}
                      </p>
                    </div>
                  )}
                  {keyTerms.lease_type_detected && (
                    <div className="p-4 rounded-lg" style={{ backgroundColor: isDarkMode ? '#1F2937' : '#F8FAFC' }}>
                      <p className="text-xs font-semibold mb-1" style={{ color: colors.textSecondary }}>{strings.leaseType}</p>
                      <p className="font-medium capitalize" style={{ color: colors.textPrimary }}>{keyTerms.lease_type_detected.replace('_', ' ')}</p>
                    </div>
                  )}
                  {keyTerms.language_detected && (
                    <div className="p-4 rounded-lg" style={{ backgroundColor: isDarkMode ? '#1F2937' : '#F8FAFC' }}>
                      <p className="text-xs font-semibold mb-1" style={{ color: colors.textSecondary }}>{strings.language}</p>
                      <p className="font-medium uppercase" style={{ color: colors.textPrimary }}>{keyTerms.language_detected}</p>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          )}

          {/* Detailed Flags */}
          {fullFlags.length > 0 && (
            <Card className="mb-6 border-none shadow-lg" style={{ backgroundColor: colors.cardBg }}>
              <CardHeader className="border-b" style={{ borderColor: colors.borderColor }}>
                <CardTitle className="flex items-center gap-2" style={{ color: colors.textPrimary }}>
                  <AlertTriangle className="w-5 h-5 text-amber-600" />
                  {strings.detailedIssues} ({fullFlags.length}{hiddenFlagsCount > 0 ? ` / ${totalFlags}` : ''})
                </CardTitle>
              </CardHeader>
              <CardContent className="p-6">
                <div className="space-y-4">
                  {fullFlags.map((flag, index) => {
                    const SeverityIcon = getSeverityIcon(flag.severity);
                    return (
                      <div key={index} className={`p-5 rounded-xl border-2 ${getSeverityColor(flag.severity)}`} style={isDarkMode ? { backgroundColor: colors.cardBg, borderColor: colors.borderColor } : {}}>
                        <div className="flex items-start gap-3 mb-3">
                          <SeverityIcon className="w-6 h-6 mt-0.5 flex-shrink-0" />
                          <div className="flex-1">
                            <div className="flex items-center justify-between mb-2">
                              <h4 className="font-bold text-lg" style={{ color: colors.textPrimary }}>{flag.title}</h4>
                              <Badge variant="outline" className="text-xs font-bold uppercase">
                                {flag.severity}
                              </Badge>
                            </div>
                            <Badge variant="outline" className="mb-3 text-xs">
                              {flag.category}
                            </Badge>
                          </div>
                        </div>
                        
                        <div className="space-y-3 ml-9">
                          <div>
                            <p className="text-xs font-bold uppercase tracking-wide mb-1 opacity-70" style={{ color: colors.textSecondary }}>{strings.evidence}</p>
                            <p className="text-sm italic border-l-2 border-current pl-3 py-1" style={{ color: colors.textPrimary }}>"{flag.evidence}"</p>
                          </div>
                          
                          <div>
                            <p className="text-xs font-bold uppercase tracking-wide mb-1 opacity-70" style={{ color: colors.textSecondary }}>{strings.explanation}</p>
                            <p className="text-sm leading-relaxed" style={{ color: colors.textPrimary }}>{flag.explanation}</p>
                          </div>
                          
                          <div className="rounded-lg p-3 border border-current/20" style={{ backgroundColor: isDarkMode ? colors.bg : 'white' }}>
                            <p className="text-xs font-bold uppercase tracking-wide mb-1 opacity-70" style={{ color: colors.textSecondary }}>{strings.recommendation}</p>
                            <p className="text-sm font-medium leading-relaxed" style={{ color: colors.textPrimary }}>{flag.recommendation}</p>
                          </div>
                          
                          {(flag.impact_0_10 || flag.likelihood_0_10) && (
                            <div className="flex gap-4 text-xs" style={{ color: colors.textSecondary }}>
                              {flag.impact_0_10 && (
                                <div>
                                  <span className="font-semibold">{strings.impact}:</span> {flag.impact_0_10}/10
                                </div>
                              )}
                              {flag.likelihood_0_10 && (
                                <div>
                                  <span className="font-semibold">{strings.likelihood}:</span> {flag.likelihood_0_10}/10
                                </div>
                              )}
                            </div>
                          )}
                        </div>
                      </div>
                    );
                  })}
                  
                  {/* SHOW UPGRADE CTA IF FLAGS ARE HIDDEN */}
                  {hiddenFlagsCount > 0 && (
                    <div className="p-6 rounded-xl border-2 border-dashed" style={{
                      backgroundColor: isDarkMode ? '#2A2D30' : '#FEF9C3',
                      borderColor: isDarkMode ? '#C7A338' : '#EAB308'
                    }}>
                      <div className="flex items-start gap-4">
                        <div className="w-10 h-10 bg-amber-500 rounded-full flex items-center justify-center flex-shrink-0">
                          <AlertTriangle className="w-5 h-5 text-white" />
                        </div>
                        <div className="flex-1">
                          <h4 className="font-bold mb-2" style={{ color: colors.textPrimary }}>
                            {language === 'th' 
                              ? `เหลืออีก ${hiddenFlagsCount} ปัญหาโดยละเอียด` 
                              : `${hiddenFlagsCount} More Detailed Issue${hiddenFlagsCount > 1 ? 's' : ''}`}
                          </h4>
                          <p className="text-sm mb-3" style={{ color: colors.textSecondary }}>
                            {language === 'th' 
                              ? 'อัปเกรดเป็น Protect หรือ Secure เพื่อดูการวิเคราะห์ทั้งหมดพร้อมคำแนะนำโดยละเอียด'
                              : 'Upgrade to Protect or Secure to view complete analysis with detailed recommendations'}
                          </p>
                          <Button
                            onClick={() => navigate(createPageUrl("Account"))}
                            className="w-full bg-gradient-to-r from-amber-600 to-amber-700 hover:from-amber-700 hover:to-amber-800"
                          >
                            {language === 'th' ? 'อัปเกรดเพื่อปลดล็อค' : 'Upgrade to Unlock'}
                          </Button>
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          )}

          {/* Missing Protections */}
          {missingItems.length > 0 && (
            <Card className="mb-6 border-none shadow-lg" style={{ backgroundColor: colors.cardBg }}>
              <CardHeader className="border-b" style={{ borderColor: colors.borderColor }}>
                <CardTitle className="flex items-center gap-2" style={{ color: colors.textPrimary }}>
                  <AlertCircle className="w-5 h-5 text-amber-600" />
                  {strings.missingProtections} ({missingItems.length})
                </CardTitle>
              </CardHeader>
              <CardContent className="p-6">
                <div className="grid md:grid-cols-2 gap-3">
                  {missingItems.map((item, index) => (
                    <div key={index} className="flex items-start gap-2 p-3 rounded-lg border border-amber-200" style={{ backgroundColor: isDarkMode ? '#1F2937' : '#FFFBEB' }}>
                      <AlertCircle className="w-4 h-4 text-amber-600 mt-0.5 flex-shrink-0" />
                      <p className="text-sm text-amber-900 leading-relaxed" style={{ color: isDarkMode ? colors.textPrimary : '#B45309' }}>{item}</p>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}

          {/* Next Steps - Enhanced with Auto-Generate */}
          <Card className="border-none shadow-lg" style={{ 
            backgroundColor: colors.cardBg,
            background: isDarkMode 
              ? 'linear-gradient(to br, #2A2D30, #1F2937)' 
              : 'linear-gradient(to br, #F0FDF4, #DBEAFE)'
          }}>
            <CardContent className="p-6">
              <h3 className="font-bold text-lg mb-4" style={{ color: colors.textPrimary }}>
                {strings.suggestedNextSteps}
              </h3>

              {/* Auto-Generate Letters - Secure Tier Only */}
              {isSecureTier ? (
                <div className="mb-4 p-4 rounded-xl border-2" style={{
                  backgroundColor: isDarkMode ? '#1F2937' : '#FFFFFF',
                  borderColor: '#C7A338'
                }}>
                  <div className="flex items-start gap-4">
                    <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-purple-600 to-purple-800 flex items-center justify-center flex-shrink-0">
                      <Sparkles className="w-6 h-6 text-white" />
                    </div>
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-2">
                        <h4 className="font-bold" style={{ color: colors.textPrimary }}>
                          {strings.autoGenerateLetters}
                        </h4>
                        <Badge className="bg-purple-100 text-purple-700 border-purple-200">
                          <Crown className="w-3 h-3 mr-1" />
                          {strings.secureTierOnly}
                        </Badge>
                      </div>
                      <p className="text-sm mb-3" style={{ color: colors.textSecondary }}>
                        {strings.autoGenerateDesc}
                      </p>
                      
                      {generationResult ? (
                        <div className="space-y-2">
                          <div className="flex items-center gap-2 p-3 rounded-lg bg-emerald-50 border border-emerald-200" style={{ backgroundColor: isDarkMode ? '#1F2937' : '#D1FAE5' }}>
                            <CheckCircle2 className="w-5 h-5 text-emerald-600" />
                            <div>
                              <p className="font-semibold text-emerald-900" style={{ color: isDarkMode ? colors.textPrimary : '#065F46' }}>
                                {strings.generated}
                              </p>
                              <p className="text-sm text-emerald-700" style={{ color: isDarkMode ? colors.textSecondary : '#047857' }}>
                                {generationResult.totalGenerated} {strings.lettersGenerated}
                              </p>
                            </div>
                          </div>
                          <Button
                            onClick={() => navigate(createPageUrl("CaseDetails") + `?caseId=${generationResult.caseId}`)}
                            className="w-full bg-emerald-600 hover:bg-emerald-700"
                          >
                            {strings.viewLetters}
                          </Button>
                        </div>
                      ) : (
                        <Button
                          onClick={analyzeAndGenerateLetters}
                          disabled={generatingLetters}
                          className="w-full bg-gradient-to-r from-purple-600 to-purple-700 hover:from-purple-700 hover:to-purple-800"
                        >
                          {generatingLetters ? (
                            <>
                              <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                              {strings.generating}
                            </>
                          ) : (
                            <>
                              <Sparkles className="w-4 h-4 mr-2" />
                              {strings.autoGenerateLetters}
                            </>
                          )}
                        </Button>
                      )}
                    </div>
                  </div>
                </div>
              ) : (
                <div className="mb-4 p-4 rounded-xl border-2 border-dashed" style={{
                  backgroundColor: isDarkMode ? '#2A2D30' : '#F9FAFB',
                  borderColor: colors.borderColor
                }}>
                  <div className="flex items-start gap-4">
                    <div className="w-12 h-12 rounded-xl bg-slate-200 flex items-center justify-center flex-shrink-0" style={{ backgroundColor: isDarkMode ? '#3A3D40' : '#E2E8F0' }}>
                      <Lock className="w-6 h-6 text-slate-500" style={{ color: isDarkMode ? colors.textSecondary : '#64748b' }} />
                    </div>
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-2">
                        <h4 className="font-bold" style={{ color: colors.textPrimary }}>
                          {strings.autoGenerateLetters}
                        </h4>
                        <Badge className="bg-purple-100 text-purple-700 border-purple-200">
                          <Crown className="w-3 h-3 mr-1" />
                          {strings.secureTierOnly}
                        </Badge>
                      </div>
                      <p className="text-sm mb-3" style={{ color: colors.textSecondary }}>
                        {strings.upgradeDesc}
                      </p>
                      <Button
                        onClick={() => navigate(createPageUrl("Account"))}
                        variant="outline"
                        className="w-full border-purple-600 text-purple-600 hover:bg-purple-50"
                        style={isDarkMode ? { borderColor: '#8B5CF6', color: '#8B5CF6', backgroundColor: '#3A3D40' } : {}}
                      >
                        <Crown className="w-4 h-4 mr-2" />
                        {strings.upgradeToSecure}
                      </Button>
                    </div>
                  </div>
                </div>
              )}

              {/* Other suggested actions */}
              <div className="grid md:grid-cols-2 gap-3">
                <Button
                  variant="outline"
                  className="justify-start h-auto py-4"
                  onClick={() => navigate(createPageUrl("DepositTracker"))}
                  style={isDarkMode ? { backgroundColor: colors.cardBg, borderColor: colors.borderColor, color: colors.textPrimary } : {}}
                >
                  <Shield className="w-5 h-5 mr-3 text-emerald-600" />
                  <div className="text-left">
                    <div className="font-semibold" style={{ color: colors.textPrimary }}>
                      {strings.enableDepositShield}
                    </div>
                    <div className="text-xs" style={{ color: colors.textSecondary }}>
                      {strings.trackYourSecurityDeposit}
                    </div>
                  </div>
                </Button>
                <Button
                  variant="outline"
                  className="justify-start h-auto py-4"
                  onClick={() => navigate(createPageUrl("Templates"))}
                  style={isDarkMode ? { backgroundColor: colors.cardBg, borderColor: colors.borderColor, color: colors.textPrimary } : {}}
                >
                  <FileText className="w-5 h-5 mr-3 text-blue-600" />
                  <div className="text-left">
                    <div className="font-semibold" style={{ color: colors.textPrimary }}>
                      {strings.generateLetter}
                    </div>
                    <div className="text-xs" style={{ color: colors.textSecondary }}>
                      {strings.professionalTenantLetters}
                    </div>
                  </div>
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </FeatureGate>
  );
}
