import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Download, Shield, FileText, ArrowLeft, AlertTriangle, Info, CheckCircle2, AlertCircle, Sparkles, Loader2, Crown, Lock } from "lucide-react";
import { FeatureGate } from "../components/shared/FeatureGate";
import AuthGuard from "../components/shared/AuthGuard";
import { haptic } from "../components/shared/HapticFeedback";
import { ToastProvider, useToast } from "../components/shared/Toast";
import PageHeader from "../components/shared/PageHeader";
import EmptyState from "../components/shared/EmptyState";
import SkeletonLoader from "../components/shared/SkeletonLoader";

function ReportFullContent() {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const toast = useToast();
  const urlParams = new URLSearchParams(window.location.search);
  const scanId = urlParams.get('scanId');
  
  const [generatingLetters, setGeneratingLetters] = useState(false);
  const [generationResult, setGenerationResult] = useState(null);
  const [downloadingPDF, setDownloadingPDF] = useState(false);

  const { data: user } = useQuery({
    queryKey: ['currentUser'],
    queryFn: () => base44.auth.me(),
  });

  const { data: scan, isLoading: scanLoading } = useQuery({
    queryKey: ['scan', scanId],
    queryFn: async () => {
      const scans = await base44.entities.LeaseScan.list();
      return scans.find(s => s.id === scanId);
    },
    enabled: !!scanId,
  });

  const { data: lease, isLoading: leaseLoading } = useQuery({
    queryKey: ['lease', scan?.lease_id],
    queryFn: async () => {
      const leases = await base44.entities.Lease.list();
      return leases.find(l => l.id === scan.lease_id);
    },
    enabled: !!scan?.lease_id,
  });

  const isLoading = scanLoading || leaseLoading;

  const language = user?.language || 'en';
  const isDarkMode = user?.theme === 'dark';
  const isSecureTier = user?.plan_tier === 'secure';
  const userTier = user?.plan_tier || 'free';

  const colors = isDarkMode ? {
    bg: '#1A1D1F',
    cardBg: '#2A2D30',
    textPrimary: '#ECEFED',
    textSecondary: '#A8ABAD',
    borderColor: '#3A3D40'
  } : {
    bg: '#F8FAFC',
    cardBg: '#FFFFFF',
    textPrimary: '#1A1D1F',
    textSecondary: '#64748b',
    borderColor: '#E5E7EB'
  };

  const t = {
    en: {
      autoGenerateLetters: "Auto-Generate Letters",
      autoGenerateDesc: "Automatically creates negotiation letters based on your scan results",
      secureTierOnly: "Secure Tier Only",
      generating: "Analysing scan & generating...",
      generated: "Letters Generated!",
      viewLetters: "View Letters",
      upgradeToSecure: "Upgrade to Secure",
      upgradeDesc: "Get automatic letter generation based on your lease scan findings",
      lettersGenerated: "letter generated successfully",
      analysisComplete: "Letter created from scan recommendations",
      noScanReportFound: "No scan report found",
      uploadALease: "Upload a Lease",
      fullLeaseReport: "Full Lease Report",
      downloadPDF: "Download PDF",
      riskAssessment: "Risk Assessment",
      score: "Score",
      keyLeaseTerms: "Key Lease Terms",
      propertyAddress: "Property Address",
      monthlyRent: "Monthly Rent",
      securityDeposit: "Security Deposit",
      leasePeriod: "Lease Period",
      leaseStart: "Lease Start",
      leaseEnd: "Lease End",
      leaseType: "Lease Type",
      language: "Language",
      detailedIssues: "Detailed Issues & Recommendations",
      evidence: "Evidence",
      explanation: "Explanation",
      recommendation: "Recommendation",
      impact: "Impact",
      likelihood: "Likelihood",
      missingProtections: "Missing Protections",
      suggestedNextSteps: "Suggested Next Steps",
      enableDepositShield: "Enable Deposit Shield",
      trackYourSecurityDeposit: "Track your security deposit",
      generateLetter: "Generate Letter",
      professionalTenantLetters: "Professional tenant letters",
      failedToGenerateLetters: "Failed to generate letters. Please try again.",
      moreDetailedIssues: "More Detailed Issue(s)",
      upgradeToUnlock: "Upgrade to Unlock",
      backToSummary: "Back to Summary"
    },
    th: {
      autoGenerateLetters: "สร้างจดหมายอัตโนมัติ",
      autoGenerateDesc: "สร้างจดหมายเจรจาโดยอัตโนมัติตามผลการสแกนของคุณ",
      secureTierOnly: "สำหรับ Secure เท่านั้น",
      generating: "กำลังวิเคราะห์และสร้าง...",
      generated: "สร้างจดหมายเรียบร้อย!",
      viewLetters: "ดูจดหมาย",
      upgradeToSecure: "อัปเกรดเป็น Secure",
      upgradeDesc: "รับการสร้างจดหมายอัตโนมัติตามผลการสแกนสัญญาเช่าของคุณ",
      lettersGenerated: "สร้างจดหมายสำเร็จแล้ว",
      analysisComplete: "สร้างจดหมายจากคำแนะนำของการสแกน",
      noScanReportFound: "ไม่พบรายงานการสแกน",
      uploadALease: "อัปโหลดสัญญาเช่า",
      fullLeaseReport: "รายงานการเช่าฉบับเต็ม",
      downloadPDF: "ดาวน์โหลด PDF",
      riskAssessment: "การประเมินความเสี่ยง",
      score: "คะแนน",
      keyLeaseTerms: "ข้อกำหนดสัญญาเช่าที่สำคัญ",
      propertyAddress: "ที่อยู่ทรัพย์สิน",
      monthlyRent: "ค่าเช่ารายเดือน",
      securityDeposit: "เงินประกัน",
      leasePeriod: "ระยะเวลาเช่า",
      leaseStart: "วันเริ่มสัญญา",
      leaseEnd: "วันสิ้นสุดสัญญา",
      leaseType: "ประเภทสัญญาเช่า",
      language: "ภาษา",
      detailedIssues: "ปัญหาและข้อแนะนำโดยละเอียด",
      evidence: "หลักฐาน",
      explanation: "คำอธิบาย",
      recommendation: "ข้อแนะนำ",
      impact: "ผลกระทบ",
      likelihood: "โอกาส",
      missingProtections: "การป้องกันที่ขาดหายไป",
      suggestedNextSteps: "ขั้นตอนที่แนะนำ",
      enableDepositShield: "เปิดใช้งาน Deposit Shield",
      trackYourSecurityDeposit: "ติดตามเงินมัดจำของคุณ",
      generateLetter: "สร้างจดหมาย",
      professionalTenantLetters: "จดหมายสำหรับผู้เช่ามืออาชีพ",
      failedToGenerateLetters: "ไม่สามารถสร้างจดหมายได้ กรุณาลองอีกครั้ง",
      moreDetailedIssues: "เหลืออีก {count} ปัญหาโดยละเอียด",
      upgradeToUnlock: "อัปเกรดเพื่อปลดล็อค",
      backToSummary: "กลับไปที่สรุป"
    },
    zh: {
      autoGenerateLetters: "自动生成信件",
      autoGenerateDesc: "根据您的扫描结果自动创建谈判信件",
      secureTierOnly: "仅限安全层",
      generating: "正在分析扫描并生成...",
      generated: "信件已生成！",
      viewLetters: "查看信件",
      upgradeToSecure: "升级到安全层",
      upgradeDesc: "根据您的租约扫描结果获取自动信件生成",
      lettersGenerated: "信件生成成功",
      analysisComplete: "分析完成 - 根据扫描建议创建信件",
      noScanReportFound: "未找到扫描报告",
      uploadALease: "上传租约",
      fullLeaseReport: "完整租约报告",
      downloadPDF: "下载PDF",
      riskAssessment: "风险评估",
      score: "评分",
      keyLeaseTerms: "关键租约条款",
      propertyAddress: "物业地址",
      monthlyRent: "月租金",
      securityDeposit: "押金",
      leasePeriod: "租期",
      leaseStart: "租约开始",
      leaseEnd: "租约结束",
      leaseType: "租约类型",
      language: "语言",
      detailedIssues: "详细问题与建议",
      evidence: "证据",
      explanation: "解释",
      recommendation: "建议",
      impact: "影响",
      likelihood: "可能性",
      missingProtections: "缺失的保护",
      suggestedNextSteps: "建议的下一步",
      enableDepositShield: "启用押金盾",
      trackYourSecurityDeposit: "追踪您的押金",
      generateLetter: "生成信件",
      professionalTenantLetters: "专业租户信件",
      failedToGenerateLetters: "生成信件失败。请重试。",
      moreDetailedIssues: "{count} 个更详细的问题",
      upgradeToUnlock: "升级以解锁",
      backToSummary: "返回摘要"
    },
    ja: {
      autoGenerateLetters: "自動レター生成",
      autoGenerateDesc: "スキャン結果に基づいて交渉レターを自動作成",
      secureTierOnly: "セキュアティアのみ",
      generating: "スキャンを分析して生成中...",
      generated: "レター生成完了！",
      viewLetters: "レターを表示",
      upgradeToSecure: "セキュアにアップグレード",
      upgradeDesc: "賃貸契約スキャン結果に基づく自動レター生成を取得",
      lettersGenerated: "レターが正常に生成されました",
      analysisComplete: "分析完了 - スキャン推奨事項からレターを作成",
      noScanReportFound: "スキャンレポートが見つかりません",
      uploadALease: "賃貸契約をアップロード",
      fullLeaseReport: "完全な賃貸レポート",
      downloadPDF: "PDFをダウンロード",
      riskAssessment: "リスク評価",
      score: "スコア",
      keyLeaseTerms: "主要な賃貸条件",
      propertyAddress: "物件住所",
      monthlyRent: "月額家賃",
      securityDeposit: "敷金",
      leasePeriod: "賃貸期間",
      leaseStart: "契約開始",
      leaseEnd: "契約終了",
      leaseType: "賃貸タイプ",
      language: "言語",
      detailedIssues: "詳細な問題と推奨事項",
      evidence: "証拠",
      explanation: "説明",
      recommendation: "推奨事項",
      impact: "影響",
      likelihood: "可能性",
      missingProtections: "不足している保護",
      suggestedNextSteps: "推奨される次のステップ",
      enableDepositShield: "デポジットシールドを有効化",
      trackYourSecurityDeposit: "敷金を追跡",
      generateLetter: "レターを生成",
      professionalTenantLetters: "プロフェッショナルな賃借人レター",
      failedToGenerateLetters: "レターの生成に失敗しました。もう一度お試しください。",
      moreDetailedIssues: "その他 {count} 件の詳細な問題",
      upgradeToUnlock: "アップグレードしてロック解除",
      backToSummary: "概要に戻る"
    },
    ko: {
      autoGenerateLetters: "자동 편지 생성",
      autoGenerateDesc: "스캔 결과를 기반으로 협상 편지를 자동 생성합니다",
      secureTierOnly: "시큐어 티어 전용",
      generating: "스캔 분석 및 생성 중...",
      generated: "편지 생성 완료!",
      viewLetters: "편지 보기",
      upgradeToSecure: "시큐어로 업그레이드",
      upgradeDesc: "임대 계약 스캔 결과를 기반으로 자동 편지 생성 받기",
      lettersGenerated: "편지가 성공적으로 생성되었습니다",
      analysisComplete: "분석 완료 - 스캔 권장사항에서 편지 생성됨",
      noScanReportFound: "스캔 보고서를 찾을 수 없음",
      uploadALease: "임대 계약 업로드",
      fullLeaseReport: "전체 임대 보고서",
      downloadPDF: "PDF 다운로드",
      riskAssessment: "위험 평가",
      score: "점수",
      keyLeaseTerms: "주요 임대 조건",
      propertyAddress: "부동산 주소",
      monthlyRent: "월 임대료",
      securityDeposit: "보증금",
      leasePeriod: "임대 기간",
      leaseStart: "계약 시작",
      leaseEnd: "계약 종료",
      leaseType: "임대 유형",
      language: "언어",
      detailedIssues: "상세 문제 및 권장사항",
      evidence: "증거",
      explanation: "설명",
      recommendation: "권장사항",
      impact: "영향",
      likelihood: "가능성",
      missingProtections: "누락된 보호",
      suggestedNextSteps: "제안된 다음 단계",
      enableDepositShield: "보증금 실드 활성화",
      trackYourSecurityDeposit: "보증금 추적",
      generateLetter: "편지 생성",
      professionalTenantLetters: "전문 임차인 편지",
      failedToGenerateLetters: "편지 생성에 실패했습니다. 다시 시도해주세요.",
      moreDetailedIssues: "{count}개의 상세 문제 더 보기",
      upgradeToUnlock: "업그레이드하여 잠금 해제",
      backToSummary: "요약으로 돌아가기"
    }
  };

  const strings = t[language] || t.en;

  const handleDownloadPDF = async () => {
    if (!scan || !lease) return;

    setDownloadingPDF(true);
    haptic.medium();

    try {
      // Generate comprehensive PDF report content
      const pdfData = {
        lease_address: lease.property_address || 'Lease Agreement',
        risk_score: scan.risk_score,
        summary: scan.summary,
        flags: scan.scan_full?.flags || [],
        missing_items: scan.scan_full?.missing_items || [],
        key_terms: scan.scan_full?.key_terms || {},
        lease_start: lease.start_date,
        lease_end: lease.end_date,
        rent_amount: lease.rent_amount,
        deposit_amount: lease.deposit_amount,
        generated_date: new Date().toISOString()
      };

      // Call PDF generation function
      const response = await base44.functions.invoke('generateLeaseReportPDF', {
        scanData: pdfData,
        language: language
      });

      if (response.data?.pdf_url) {
        // Download via new tab (works on Android Chrome)
        const link = document.createElement('a');
        link.href = response.data.pdf_url;
        link.download = `LeaseShield-Report-${lease.id.substring(0, 8)}.pdf`;
        link.target = '_blank';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        
        toast.success(language === 'th' ? 'กำลังดาวน์โหลด PDF' : 'Downloading PDF');
        haptic.success();
      } else {
        throw new Error('PDF generation failed');
      }
    } catch (error) {
      console.error('PDF download failed:', error);
      toast.error(language === 'th' ? 'ไม่สามารถสร้าง PDF ได้ กรุณาลองอีกครั้ง' : 'Failed to generate PDF. Please try again.');
      haptic.error();
    } finally {
      setDownloadingPDF(false);
    }
  };

  // Generate negotiation letter from scan recommendations
  const analyzeAndGenerateLetters = async () => {
    if (!lease || !user) {
      const missingData = { lease: !!lease, user: !!user };
      console.error('[LETTER_GENERATION_ERROR] Missing required data:', missingData);
      toast.error(`Cannot generate letter: Missing ${!lease ? 'lease' : 'user'} data`);
      return;
    }

    console.log('[Letter Generation] Starting:', { 
      userId: user.id,
      userEmail: user.email,
      leaseId: lease.id, 
      scanId: scan?.id || 'no-scan',
      riskScore: scan?.risk_score || 0,
      flagsCount: scan?.scan_full?.flags?.length || 0,
      hasScanData: !!scan
    });

    setGeneratingLetters(true);
    setGenerationResult(null);

    try {
      // Build letter content - handle missing/incomplete scan data gracefully
      const fullFlags = scan?.scan_full?.flags || scan?.flags || [];
      const riskScore = scan?.risk_score || 0;
      const summary = scan?.summary || '';

      console.log('[Letter Generation] Scan data:', { 
        flagsAvailable: fullFlags.length,
        riskScore,
        hasSummary: !!summary
      });

      let letterBody = '';
      let recommendationsUsed = [];

      if (fullFlags.length > 0) {
        // Generate from recommendations
        const topIssues = fullFlags.slice(0, 5);
        recommendationsUsed = topIssues.map(f => f.title || f.category || 'Unknown');
        
        const issuesList = topIssues.map((flag, idx) => {
          const title = flag.title || flag.category || 'Issue';
          const explanation = flag.explanation || flag.description || 'This clause may require review';
          const recommendation = flag.recommendation || 'Please consider reviewing this clause';
          return `${idx + 1}. ${title}\n   ${explanation}\n   Recommendation: ${recommendation}`;
        }).join('\n\n');

        letterBody = `Dear Landlord,

I am writing regarding the lease agreement for ${lease.property_address || 'the property'}.

After carefully reviewing the lease terms, I have identified several points that I would like to discuss and potentially amend before signing:

${issuesList}

I believe these amendments would create a more balanced agreement that protects both parties' interests. I would appreciate the opportunity to discuss these points with you.

Thank you for your consideration.

Sincerely,
${user.full_name || 'Tenant'}`;
      } else if (riskScore > 0) {
        // Generic letter based on risk score
        console.log('[Letter Generation] No flags, generating generic letter based on risk score');
        
        const riskLevel = riskScore >= 70 ? 'high' : riskScore >= 40 ? 'medium' : 'low';
        const riskText = riskScore >= 70 
          ? 'several significant concerns' 
          : riskScore >= 40 
            ? 'some areas that warrant discussion'
            : 'a few points for clarification';

        letterBody = `Dear Landlord,

I am writing regarding the lease agreement for ${lease.property_address || 'the property'}.

After reviewing the lease terms, I have identified ${riskText} that I would like to discuss before signing. Based on my analysis, the lease has a risk score of ${riskScore}/100, which suggests that some clauses may benefit from clarification or amendment.

I would appreciate the opportunity to discuss these matters with you to ensure we have a fair and balanced agreement that protects both parties' interests.

The main areas I'd like to review include:
- Security deposit terms and return conditions
- Maintenance and repair responsibilities
- Notice periods and termination procedures
- Rent adjustment clauses
- Landlord access and privacy rights

Thank you for your consideration. I look forward to discussing these points with you.

Sincerely,
${user.full_name || 'Tenant'}`;
        recommendationsUsed = ['generic_risk_based'];
      } else {
        // Minimal fallback letter
        console.log('[Letter Generation] No scan data, generating minimal fallback letter');
        
        letterBody = `Dear Landlord,

I am writing regarding the lease agreement for ${lease.property_address || 'the property'}.

I would like to request an opportunity to discuss the lease terms before signing to ensure I fully understand all clauses and that we have a mutually beneficial agreement.

Could we schedule a time to review the following:
- Security deposit terms
- Maintenance responsibilities
- Notice requirements
- Any special conditions

Thank you for your time and consideration.

Sincerely,
${user.full_name || 'Tenant'}`;
        recommendationsUsed = ['minimal_fallback'];
      }

      const letterData = {
        user_id: user.id,
        lease_id: lease.id,
        scan_id: scan?.id || null,
        title: `Lease Negotiation Letter - ${lease.property_address || 'Property'}`,
        language: language,
        body: letterBody,
        format: 'text',
        status: 'draft',
        recommendations_used: recommendationsUsed
      };

      console.log('[Letter Generation] Creating Letter with data:', { 
        user_id: letterData.user_id,
        lease_id: letterData.lease_id,
        scan_id: letterData.scan_id,
        titleLength: letterData.title.length,
        bodyLength: letterData.body.length,
        recommendationsCount: recommendationsUsed.length
      });

      // Create Letter record
      let newLetter;
      try {
        newLetter = await base44.entities.Letter.create(letterData);
        console.log('[Letter Generation] Create response:', newLetter);
      } catch (createError) {
        console.error('[LETTER_GENERATION_ERROR] Database create failed:', {
          error: createError,
          message: createError.message,
          stack: createError.stack,
          name: createError.name,
          response: createError.response?.data
        });
        throw new Error(`Database error: ${createError.message || 'Failed to save letter'}`);
      }

      if (!newLetter || !newLetter.id) {
        console.error('[LETTER_GENERATION_ERROR] No ID returned:', newLetter);
        throw new Error('Failed to create letter - no ID returned from database');
      }

      console.log('[Letter Generation] Success:', { 
        letterId: newLetter.id,
        recommendationsUsed: recommendationsUsed.length,
        letterCreated: true
      });

      // Verify letter was created
      try {
        const verifyLetters = await base44.entities.Letter.filter({ id: newLetter.id });
        console.log('[Letter Generation] Verification query:', {
          letterId: newLetter.id,
          found: verifyLetters.length > 0
        });

        if (verifyLetters.length === 0) {
          console.error('[LETTER_GENERATION_ERROR] Letter not found after creation - possible RLS issue');
          throw new Error('Letter created but not retrievable - check permissions');
        }
      } catch (verifyError) {
        console.error('[LETTER_GENERATION_ERROR] Verification failed:', verifyError);
        // Don't fail the whole operation if verification fails - letter was created
      }

      setGenerationResult({
        letterId: newLetter.id,
        totalGenerated: 1
      });

      queryClient.invalidateQueries({ queryKey: ['letters'] });
      queryClient.invalidateQueries({ queryKey: ['letter', newLetter.id] });
      
      toast.success(language === 'th' ? 'สร้างจดหมายเรียบร้อย' : 'Letter generated successfully');
      haptic.success();

    } catch (error) {
      console.error('[LETTER_GENERATION_ERROR] Full error:', {
        message: error.message,
        stack: error.stack,
        name: error.name,
        error: error
      });
      
      const errorMessage = error.message || 'Unknown error occurred';
      toast.error(`Failed to generate letter: ${errorMessage}`);
      haptic.error();
      setGenerationResult(null);
    } finally {
      setGeneratingLetters(false);
    }
  };

  if (isLoading) {
    return (
      <div className="min-h-screen p-6 page-transition" style={{ backgroundColor: colors.bg }}>
        <div className="max-w-4xl mx-auto">
          <SkeletonLoader variant="card" count={3} isDarkMode={isDarkMode} />
        </div>
      </div>
    );
  }

  if (!scan || !lease) {
    return (
      <div className="min-h-screen p-6 page-transition" style={{ backgroundColor: colors.bg }}>
        <div className="max-w-4xl mx-auto">
          <Card className="border-none shadow-xl" style={{ backgroundColor: colors.cardBg }}>
            <CardContent className="p-0">
              <EmptyState
                icon={FileText}
                title={strings.noScanReportFound}
                description=""
                actionLabel={strings.uploadALease}
                onAction={() => navigate(createPageUrl("UploadScan"))}
                isDarkMode={isDarkMode}
              />
            </CardContent>
          </Card>
        </div>
      </div>
    );
  }

  const getSeverityIcon = (severity) => {
    const icons = { critical: AlertTriangle, high: AlertTriangle, medium: Info, low: CheckCircle2 };
    return icons[severity] || Info;
  };

  const getSeverityColor = (severity) => {
    const colors = {
      critical: "text-red-600 bg-red-50 border-red-200",
      high: "text-orange-600 bg-orange-50 border-orange-200",
      medium: "text-amber-600 bg-amber-50 border-amber-200",
      low: "text-emerald-600 bg-emerald-50 border-emerald-200"
    };
    return colors[severity] || "text-slate-600 bg-slate-50 border-slate-200";
  };

  const getRiskLevel = (score) => {
    if (score >= 70) return { level: 'high', label: language === 'th' ? 'ความเสี่ยงสูง' : language === 'ru' ? 'Высокий риск' : 'HIGH RISK', color: '#EF4444', bg: '#FEE2E2' };
    if (score >= 40) return { level: 'medium', label: language === 'th' ? 'ความเสี่ยงปานกลาง' : language === 'ru' ? 'Средний риск' : 'MEDIUM RISK', color: '#F59E0B', bg: '#FEF3C7' };
    return { level: 'low', label: language === 'th' ? 'ความเสี่ยงต่ำ' : language === 'ru' ? 'Низкий риск' : 'LOW RISK', color: '#10B981', bg: '#D1FAE5' };
  };

  const riskLevel = scan ? getRiskLevel(scan.risk_score) : null;

  // LIMIT FLAGS BASED ON TIER (consistent with ScanPreview)
  const getFullDisplayFlags = () => {
    const allFlags = scan.scan_full?.flags || [];
    
    // Lite tier: Show max 5 flags
    if (userTier === 'lite') {
      return allFlags.slice(0, 5);
    }
    
    // Free tier shouldn't access this page, but if they do, show 4
    if (userTier === 'free') {
      return allFlags.slice(0, 4);
    }
    
    // Protect and Secure: Show all flags
    return allFlags;
  };

  const fullFlags = getFullDisplayFlags();
  const totalFlags = scan.scan_full?.flags?.length || 0;
  const hiddenFlagsCount = totalFlags - fullFlags.length;
  const missingItems = scan.scan_full?.missing_items || [];
  const keyTerms = scan.scan_full?.key_terms || {};

  return (
    <FeatureGate feature="full_report">
      <div className="min-h-screen p-4 md:p-6 page-transition" style={{ backgroundColor: colors.bg }}>
        <div className="max-w-4xl mx-auto">
          <PageHeader
            title={strings.fullLeaseReport}
            subtitle={lease.property_address || 'Lease Agreement'}
            icon={FileText}
            iconColor="#0C3B2E"
            showBack={true}
            backRoute={createPageUrl("UploadScan")}
            isDarkMode={isDarkMode}
            actions={
              <Button 
                className="btn-interaction"
                style={{ backgroundColor: '#0C3B2E', color: '#FFFFFF' }}
                onClick={handleDownloadPDF}
                disabled={downloadingPDF}
              >
                {downloadingPDF ? (
                  <>
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    {language === 'th' ? 'กำลังสร้าง...' : 'Generating...'}
                  </>
                ) : (
                  <>
                    <Download className="w-4 h-4 mr-2" />
                    {strings.downloadPDF}
                  </>
                )}
              </Button>
            }
          />

          {/* Risk Score Summary */}
          <Card className="mb-6 border-none shadow-lg" style={{ backgroundColor: colors.cardBg }}>
            <CardHeader style={{ 
              backgroundColor: riskLevel?.color || '#0C3B2E',
              color: '#FFFFFF'
            }}>
              <CardTitle className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
                <span>{strings.riskAssessment}</span>
                <div className="flex flex-wrap items-center gap-2">
                  <Badge className="text-lg px-4 py-2" style={{
                    backgroundColor: riskLevel?.bg || '#fff',
                    color: riskLevel?.color || '#1F2937',
                    border: `2px solid ${riskLevel?.color || '#D1D5DB'}`
                  }}>
                    {strings.score}: {scan.risk_score}/100
                  </Badge>
                  <Badge className="text-sm px-3 py-1.5 font-bold flex items-center gap-1" style={{
                    backgroundColor: '#FFFFFF',
                    color: riskLevel?.color || '#10B981'
                  }}>
                    {riskLevel?.level === 'high' && <AlertTriangle className="w-4 h-4" />}
                    {riskLevel?.label || 'LOW RISK'}
                  </Badge>
                </div>
              </CardTitle>
            </CardHeader>
            {riskLevel?.level === 'high' && (
              <div className="px-6 pt-4 pb-2">
                <div className="p-3 rounded-lg border-l-4" style={{
                  backgroundColor: isDarkMode ? '#3A2626' : '#FEE2E2',
                  borderLeftColor: '#EF4444'
                }}>
                  <p className="text-sm font-semibold" style={{ color: isDarkMode ? '#FCA5A5' : '#DC2626' }}>
                    {language === 'th' 
                      ? 'ความเสี่ยงสูง: สัญญานี้มีข้อกำหนดที่เอื้อประโยชน์ต่อเจ้าของบ้านอย่างมาก ตรวจสอบก่อนเซ็น'
                      : language === 'ru'
                        ? 'Высокий риск: этот договор содержит условия, которые сильно благоприятствуют арендодателю. Проверьте перед подписанием.'
                        : 'High risk: this lease contains clauses that heavily favour the landlord. Review before signing.'}
                  </p>
                </div>
              </div>
            )}
            <CardContent className="p-6">
              <p className="leading-relaxed" style={{ color: colors.textPrimary }}>{scan.summary}</p>
            </CardContent>
          </Card>

          {/* Key Terms */}
          {Object.keys(keyTerms).length > 0 && (
            <Card className="mb-6 border-none shadow-lg" style={{ backgroundColor: colors.cardBg }}>
              <CardHeader className="border-b" style={{ borderColor: colors.borderColor }}>
                <CardTitle className="flex items-center gap-2" style={{ color: colors.textPrimary }}>
                  <FileText className="w-5 h-5" style={{ color: '#0C3B2E' }} />
                  {strings.keyLeaseTerms}
                </CardTitle>
              </CardHeader>
              <CardContent className="p-6">
                <div className="grid md:grid-cols-2 gap-4">
                  {keyTerms.property_address && (
                    <div className="p-4 rounded-lg" style={{ backgroundColor: isDarkMode ? '#1F2937' : '#F8FAFC' }}>
                      <p className="text-xs font-semibold mb-1" style={{ color: colors.textSecondary }}>{strings.propertyAddress}</p>
                      <p className="font-medium" style={{ color: colors.textPrimary }}>{keyTerms.property_address}</p>
                    </div>
                  )}
                  {keyTerms.rent_amount && (
                    <div className="p-4 rounded-lg" style={{ backgroundColor: isDarkMode ? '#1F2937' : '#F8FAFC' }}>
                      <p className="text-xs font-semibold mb-1" style={{ color: colors.textSecondary }}>{strings.monthlyRent}</p>
                      <p className="font-medium" style={{ color: colors.textPrimary }}>฿{keyTerms.rent_amount.toLocaleString()}</p>
                    </div>
                  )}
                  {keyTerms.deposit_amount && (
                    <div className="p-4 rounded-lg" style={{ backgroundColor: isDarkMode ? '#1F2937' : '#F8FAFC' }}>
                      <p className="text-xs font-semibold mb-1" style={{ color: colors.textSecondary }}>{strings.securityDeposit}</p>
                      <p className="font-medium" style={{ color: colors.textPrimary }}>฿{keyTerms.deposit_amount.toLocaleString()}</p>
                    </div>
                  )}
                  {keyTerms.start_date && (
                    <div className="p-4 rounded-lg" style={{ backgroundColor: isDarkMode ? '#1F2937' : '#F8FAFC' }}>
                      <p className="text-xs font-semibold mb-1" style={{ color: colors.textSecondary }}>{strings.leasePeriod}</p>
                      <p className="font-medium" style={{ color: colors.textPrimary }}>
                        {keyTerms.start_date} {keyTerms.end_date && `to ${keyTerms.end_date}`}
                      </p>
                    </div>
                  )}
                  {keyTerms.lease_type_detected && (
                    <div className="p-4 rounded-lg" style={{ backgroundColor: isDarkMode ? '#1F2937' : '#F8FAFC' }}>
                      <p className="text-xs font-semibold mb-1" style={{ color: colors.textSecondary }}>{strings.leaseType}</p>
                      <p className="font-medium capitalize" style={{ color: colors.textPrimary }}>{keyTerms.lease_type_detected.replace('_', ' ')}</p>
                    </div>
                  )}
                  {keyTerms.language_detected && (
                    <div className="p-4 rounded-lg" style={{ backgroundColor: isDarkMode ? '#1F2937' : '#F8FAFC' }}>
                      <p className="text-xs font-semibold mb-1" style={{ color: colors.textSecondary }}>{strings.language}</p>
                      <p className="font-medium uppercase" style={{ color: colors.textPrimary }}>{keyTerms.language_detected}</p>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          )}

          {/* Detailed Flags */}
          {fullFlags.length > 0 && (
            <Card className="mb-6 border-none shadow-lg" style={{ backgroundColor: colors.cardBg }}>
              <CardHeader className="border-b" style={{ borderColor: colors.borderColor }}>
                <CardTitle className="flex items-center gap-2" style={{ color: colors.textPrimary }}>
                  <AlertTriangle className="w-5 h-5 text-amber-600" />
                  {strings.detailedIssues} ({fullFlags.length}{hiddenFlagsCount > 0 ? ` / ${totalFlags}` : ''})
                </CardTitle>
              </CardHeader>
              <CardContent className="p-6">
                <div className="space-y-4">
                  {fullFlags.map((flag, index) => {
                    const SeverityIcon = getSeverityIcon(flag.severity);
                    return (
                      <div key={index} className={`p-5 rounded-xl border-2 ${getSeverityColor(flag.severity)}`} style={isDarkMode ? { backgroundColor: colors.cardBg, borderColor: colors.borderColor } : {}}>
                        <div className="flex items-start gap-3 mb-3">
                          <SeverityIcon className="w-6 h-6 mt-0.5 flex-shrink-0" />
                          <div className="flex-1">
                            <div className="flex items-center justify-between mb-2">
                              <h4 className="font-bold text-lg" style={{ color: colors.textPrimary }}>{flag.title}</h4>
                              <Badge variant="outline" className="text-xs font-bold uppercase">
                                {flag.severity}
                              </Badge>
                            </div>
                            <Badge variant="outline" className="mb-3 text-xs">
                              {flag.category}
                            </Badge>
                          </div>
                        </div>
                        
                        <div className="space-y-3 ml-9">
                          <div>
                            <p className="text-xs font-bold uppercase tracking-wide mb-1 opacity-70" style={{ color: colors.textSecondary }}>{strings.evidence}</p>
                            <p className="text-sm italic border-l-2 border-current pl-3 py-1" style={{ color: colors.textPrimary }}>"{flag.evidence}"</p>
                          </div>
                          
                          <div>
                            <p className="text-xs font-bold uppercase tracking-wide mb-1 opacity-70" style={{ color: colors.textSecondary }}>{strings.explanation}</p>
                            <p className="text-sm leading-relaxed" style={{ color: colors.textPrimary }}>{flag.explanation}</p>
                          </div>
                          
                          <div className="rounded-lg p-3 border border-current/20" style={{ backgroundColor: isDarkMode ? colors.bg : 'white' }}>
                            <p className="text-xs font-bold uppercase tracking-wide mb-1 opacity-70" style={{ color: colors.textSecondary }}>{strings.recommendation}</p>
                            <p className="text-sm font-medium leading-relaxed" style={{ color: colors.textPrimary }}>{flag.recommendation}</p>
                          </div>
                          
                          {(flag.impact_0_10 || flag.likelihood_0_10) && (
                            <div className="flex gap-4 text-xs" style={{ color: colors.textSecondary }}>
                              {flag.impact_0_10 && (
                                <div>
                                  <span className="font-semibold">{strings.impact}:</span> {flag.impact_0_10}/10
                                </div>
                              )}
                              {flag.likelihood_0_10 && (
                                <div>
                                  <span className="font-semibold">{strings.likelihood}:</span> {flag.likelihood_0_10}/10
                                </div>
                              )}
                            </div>
                          )}
                        </div>
                      </div>
                    );
                  })}
                  
                  {/* SHOW UPGRADE CTA IF FLAGS ARE HIDDEN */}
                  {hiddenFlagsCount > 0 && (
                    <div className="p-6 rounded-xl border-2 border-dashed" style={{
                      backgroundColor: isDarkMode ? '#2A2D30' : '#FEF9C3',
                      borderColor: isDarkMode ? '#C7A338' : '#EAB308'
                    }}>
                      <div className="flex items-start gap-4">
                        <div className="w-10 h-10 bg-amber-500 rounded-full flex items-center justify-center flex-shrink-0">
                          <AlertTriangle className="w-5 h-5 text-white" />
                        </div>
                        <div className="flex-1">
                          <h4 className="font-bold mb-2" style={{ color: colors.textPrimary }}>
                            {language === 'th' 
                              ? strings.moreDetailedIssues.replace('{count}', hiddenFlagsCount)
                              : `${hiddenFlagsCount} ${strings.moreDetailedIssues.replace('{count}', hiddenFlagsCount)}`}
                          </h4>
                          <p className="text-sm mb-3" style={{ color: colors.textSecondary }}>
                            {language === 'th' 
                              ? 'อัปเกรดเป็น Protect หรือ Secure เพื่อดูการวิเคราะห์ทั้งหมดพร้อมคำแนะนำโดยละเอียด'
                              : 'Upgrade to Protect or Secure to view complete analysis with detailed recommendations'}
                          </p>
                          <Button
                            onClick={() => navigate(createPageUrl("Account") + '?highlight=plans')}
                            className="w-full bg-gradient-to-r from-amber-600 to-amber-700 hover:from-amber-700 hover:to-amber-800"
                          >
                            {strings.upgradeToUnlock}
                          </Button>
                          <Button
                            variant="outline"
                            onClick={() => navigate(createPageUrl("ScanPreview") + `?scanId=${scanId}`)}
                            className="w-full mt-2"
                            style={isDarkMode ? { borderColor: colors.borderColor, color: colors.textPrimary } : {}}
                          >
                            <ArrowLeft className="w-4 h-4 mr-2" />
                            {strings.backToSummary}
                          </Button>
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          )}

          {/* Missing Protections */}
          {missingItems.length > 0 && (
            <Card className="mb-6 border-none shadow-lg" style={{ backgroundColor: colors.cardBg }}>
              <CardHeader className="border-b" style={{ borderColor: colors.borderColor }}>
                <CardTitle className="flex items-center gap-2" style={{ color: colors.textPrimary }}>
                  <AlertCircle className="w-5 h-5 text-amber-600" />
                  {strings.missingProtections} ({missingItems.length})
                </CardTitle>
              </CardHeader>
              <CardContent className="p-6">
                <div className="grid md:grid-cols-2 gap-3">
                  {missingItems.map((item, index) => (
                    <div key={index} className="flex items-start gap-2 p-3 rounded-lg border border-amber-200" style={{ backgroundColor: isDarkMode ? '#1F2937' : '#FFFBEB' }}>
                      <AlertCircle className="w-4 h-4 text-amber-600 mt-0.5 flex-shrink-0" />
                      <p className="text-sm text-amber-900 leading-relaxed" style={{ color: isDarkMode ? colors.textPrimary : '#B45309' }}>{item}</p>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}

          {/* Next Steps - Enhanced with Auto-Generate */}
          <Card className="border-none shadow-lg" style={{ 
            backgroundColor: colors.cardBg,
            background: isDarkMode 
              ? 'linear-gradient(to br, #2A2D30, #1F2937)' 
              : 'linear-gradient(to br, #F0FDF4, #DBEAFE)'
          }}>
            <CardContent className="p-6">
              <h3 className="font-bold text-lg mb-4" style={{ color: colors.textPrimary }}>
                {strings.suggestedNextSteps}
              </h3>

              {/* Auto-Generate Letters - Secure Tier Only */}
              {isSecureTier ? (
                <div className="mb-4 rounded-xl border-2 overflow-hidden" style={{
                  backgroundColor: isDarkMode ? '#1F2937' : '#FFFFFF',
                  borderColor: '#0C3B2E'
                }}>
                  {generatingLetters ? (
                    <div className="p-6">
                      <div className="flex flex-col items-center justify-center py-6">
                        <Loader2 className="w-12 h-12 animate-spin mb-4" style={{ color: '#0C3B2E' }} />
                        <p className="font-semibold text-base mb-2" style={{ color: colors.textPrimary }}>
                          {strings.generating}
                        </p>
                        <p className="text-sm text-center" style={{ color: colors.textSecondary }}>
                          {language === 'th' 
                            ? 'กำลังสร้างจดหมายจากคำแนะนำของการสแกน...'
                            : 'Creating letter from scan recommendations...'}
                        </p>
                      </div>
                    </div>
                  ) : generationResult ? (
                    <div className="p-4">
                      <div className="flex items-start gap-4">
                        <div className="w-12 h-12 rounded-xl flex items-center justify-center flex-shrink-0" style={{
                          backgroundColor: '#10B981'
                        }}>
                          <CheckCircle2 className="w-6 h-6 text-white" />
                        </div>
                        <div className="flex-1">
                          <h4 className="font-bold mb-1" style={{ color: colors.textPrimary }}>
                            {strings.generated}
                          </h4>
                          <p className="text-sm mb-4" style={{ color: colors.textSecondary }}>
                            {language === 'th' ? 'พร้อมสำหรับการตรวจสอบและแก้ไข' : 'Ready for review and editing'}
                          </p>
                          <Button
                            onClick={() => {
                              console.log('[Navigation] Going to LeaseLetters with leaseId:', lease.id);
                              haptic.medium();
                              navigate(createPageUrl("LeaseLetters") + `?leaseId=${lease.id}`);
                            }}
                            style={{ backgroundColor: '#0C3B2E', color: '#FFFFFF' }}
                            className="w-full"
                          >
                            <FileText className="w-4 h-4 mr-2" />
                            {language === 'th' ? 'ดูจดหมาย' : 'View Letters'}
                          </Button>
                        </div>
                      </div>
                    </div>
                  ) : (
                    <div className="p-4">
                      <div className="flex items-start gap-4">
                        <div className="w-12 h-12 rounded-xl flex items-center justify-center flex-shrink-0" style={{
                          backgroundColor: '#0C3B2E'
                        }}>
                          <Sparkles className="w-6 h-6 text-white" />
                        </div>
                        <div className="flex-1">
                          <div className="flex items-center gap-2 mb-2">
                            <h4 className="font-bold" style={{ color: colors.textPrimary }}>
                              {strings.autoGenerateLetters}
                            </h4>
                            <Badge style={{ backgroundColor: '#C7A338', color: '#FFFFFF', border: 'none' }}>
                              <Crown className="w-3 h-3 mr-1" />
                              {strings.secureTierOnly}
                            </Badge>
                          </div>
                          <p className="text-sm mb-3" style={{ color: colors.textSecondary }}>
                            {strings.autoGenerateDesc}
                          </p>
                          <Button
                            onClick={() => {
                              haptic.medium();
                              analyzeAndGenerateLetters();
                            }}
                            disabled={generatingLetters}
                            className="w-full btn-interaction"
                            style={{ backgroundColor: '#0C3B2E', color: '#FFFFFF' }}
                          >
                            <Sparkles className="w-4 h-4 mr-2" />
                            {strings.autoGenerateLetters}
                          </Button>
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              ) : (
                <div className="mb-4 p-4 rounded-xl border-2 border-dashed" style={{
                  backgroundColor: isDarkMode ? '#2A2D30' : '#F9FAFB',
                  borderColor: colors.borderColor
                }}>
                  <div className="flex items-start gap-4">
                    <div className="w-12 h-12 rounded-xl bg-slate-200 flex items-center justify-center flex-shrink-0" style={{ backgroundColor: isDarkMode ? '#3A3D40' : '#E2E8F0' }}>
                      <Lock className="w-6 h-6 text-slate-500" style={{ color: isDarkMode ? colors.textSecondary : '#64748b' }} />
                    </div>
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-2">
                        <h4 className="font-bold" style={{ color: colors.textPrimary }}>
                          {strings.autoGenerateLetters}
                        </h4>
                        <Badge style={{ backgroundColor: '#C7A338', color: '#FFFFFF', border: 'none' }}>
                          <Crown className="w-3 h-3 mr-1" />
                          {strings.secureTierOnly}
                        </Badge>
                      </div>
                      <p className="text-sm mb-3" style={{ color: colors.textSecondary }}>
                        {strings.upgradeDesc}
                      </p>
                      <Button
                        onClick={() => navigate(createPageUrl("Account"))}
                        variant="outline"
                        className="w-full"
                        style={{ borderColor: '#0C3B2E', color: '#0C3B2E' }}
                      >
                        <Crown className="w-4 h-4 mr-2" />
                        {strings.upgradeToSecure}
                      </Button>
                    </div>
                  </div>
                </div>
              )}

              {/* Other suggested actions */}
              <div className="grid md:grid-cols-1 gap-3">
                <Button
                  variant="outline"
                  className="justify-start h-auto py-4"
                  onClick={() => navigate(createPageUrl("DepositTracker"))}
                  style={isDarkMode ? { backgroundColor: colors.cardBg, borderColor: colors.borderColor, color: colors.textPrimary } : {}}
                >
                  <Shield className="w-5 h-5 mr-3 text-emerald-600" />
                  <div className="text-left">
                    <div className="font-semibold" style={{ color: colors.textPrimary }}>
                      {strings.enableDepositShield}
                    </div>
                    <div className="text-xs" style={{ color: colors.textSecondary }}>
                      {strings.trackYourSecurityDeposit}
                    </div>
                  </div>
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </FeatureGate>
  );
}

export default function ReportFull() {
  return (
    <AuthGuard>
      <ToastProvider>
        <ReportFullContent />
      </ToastProvider>
    </AuthGuard>
  );
}