import { createClientFromRequest } from 'npm:@base44/sdk@0.7.1';

/**
 * Lease Shield – Save Reviewed Letter (STEP 2: Save Only - NO Credit Deduction)
 * This function saves the user-reviewed/edited letter
 * Credits were already deducted during generation
 */

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);

    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const args = await req.json();

    const {
      subject,
      letter_en,
      letter_th,
      tenant_name,
      landlord_name,
      property_address,
      caseId
    } = args;

    // Validate required fields
    if (!subject || !letter_en || !letter_th) {
      return Response.json({ error: 'Missing required fields' }, { status: 400 });
    }

    const SUBJECT_NAMES = {
      lease_negotiation: { name_en: "Pre-Signing Lease Review", name_th: "ทบทวนสัญญาก่อนลงนาม" },
      deposit: { name_en: "Deposit Return Request", name_th: "จดหมายขอคืนเงินมัดจำ" },
      deductions: { name_en: "Request for Itemised Deductions", name_th: "ขอรายละเอียดการหักเงิน" },
      reminder: { name_en: "Friendly Reminder", name_th: "จดหมายเตือนแบบมิตร" },
      dispute: { name_en: "Formal Dispute of Withholding", name_th: "จดหมายคัดค้านการระงับเงิน" },
      early_termination: { name_en: "Early Termination Reconciliation", name_th: "ประสานยุติสัญญาก่อนกำหนด" },
      condition_dispute: { name_en: "Property Condition Dispute", name_th: "โต้แย้งสภาพทรัพย์สิน" },
      evidence: { name_en: "Request for Evidence", name_th: "ขอหลักฐานประกอบ" },
      final_opportunity: { name_en: "Final Opportunity", name_th: "โอกาสสุดท้าย" },
      non_compliance: { name_en: "Notice of Non-Compliance", name_th: "แจ้งไม่ปฏิบัติตามสัญญา" },
      settlement: { name_en: "Settlement Confirmation", name_th: "ยืนยันการตกลงชำระเงิน" }
    };

    const letterConfig = SUBJECT_NAMES[subject] || { name_en: "Legal Letter", name_th: "จดหมายทางกฎหมาย" };

    const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    const todayTh = new Date().toLocaleDateString('th-TH', { year: 'numeric', month: 'long', day: 'numeric' });

    // Get tenant data from user profile
    const tenantFullAddress = [
      user.tenant_address,
      user.tenant_city,
      user.tenant_state,
      user.tenant_zip
    ].filter(Boolean).join(', ');

    // Replace placeholders in letter content
    const replacePlaceholders = (content) => {
      return content
        .replace(/\[Your Address\]/gi, user.tenant_address || '[Your Address]')
        .replace(/\[City, State, Zip Code\]/gi, 
          [user.tenant_city, user.tenant_state, user.tenant_zip].filter(Boolean).join(', ') || '[City, State, Zip Code]')
        .replace(/\[Email Address\]/gi, user.email || '[Email Address]')
        .replace(/\[Date\]/gi, today);
    };

    const processedLetterEn = replacePlaceholders(letter_en);
    const processedLetterTh = replacePlaceholders(letter_th);

    // Build HTML with reviewed content
    const htmlContent = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${letterConfig.name_en} / ${letterConfig.name_th}</title>
  <style>
    body { font-family: 'Sarabun', 'Tahoma', sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.6; color: #1a1d1f; }
    .header { border-bottom: 3px solid #0C3B2E; padding-bottom: 20px; margin-bottom: 30px; }
    .logo { font-size: 24px; font-weight: bold; color: #0C3B2E; margin-bottom: 5px; }
    .subtitle { color: #64748b; font-size: 14px; }
    .section { margin-bottom: 40px; }
    .section-title { background: #0C3B2E; color: white; padding: 10px 15px; margin-bottom: 20px; font-weight: bold; border-radius: 4px; }
    .content { padding: 0 15px; white-space: pre-wrap; }
    .footer { border-top: 2px solid #E5E7EB; padding-top: 20px; margin-top: 40px; text-align: center; font-size: 12px; color: #64748b; }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">🛡️ LEASE SHIELD</div>
    <div class="subtitle">Fair. Transparent. Protected.</div>
    <div style="margin-top: 10px; font-size: 14px; color: #64748b;">${today} / ${todayTh}</div>
  </div>

  <div class="section">
    <div class="section-title">📄 ${letterConfig.name_en}</div>
    <div class="content">${processedLetterEn}</div>
  </div>

  <div class="section">
    <div class="section-title">📄 ${letterConfig.name_th}</div>
    <div class="content">${processedLetterTh}</div>
  </div>

  <div class="footer">
    <p>Generated by Lease Shield | www.leaseshield.asia</p>
    <p>This letter is human-screened with AI assistance, tailored to your specific requirements. Please review before sending.</p>
  </div>
</body>
</html>`;

    // File naming
    const stamp = new Date().toISOString().replace(/[:.]/g, "-").substring(0, 19);
    const baseName = `${subject}_letter_${stamp}`;

    const htmlBlob = new Blob([htmlContent], { type: 'text/html; charset=utf-8' });
    const htmlFile = new File([htmlBlob], `${baseName}.html`, { type: 'text/html' });

    const { file_url: htmlUrl } = await base44.integrations.Core.UploadFile({ file: htmlFile });

    const docBlob = new Blob([htmlContent], { type: 'application/msword; charset=utf-8' });
    const docFile = new File([docBlob], `${baseName}.doc`, { type: 'application/msword' });

    const { file_url: docUrl } = await base44.integrations.Core.UploadFile({ file: docFile });

    // Create document entry
    const docEntry = await base44.entities.Document.create({
      type: 'letter',
      file_url: docUrl,
      label: `${letterConfig.name_en} / ${letterConfig.name_th}`,
      html_content: htmlContent
    });

    console.log(`✅ Reviewed letter saved successfully. No credit deduction (already done).`);

    // Update case if provided
    if (caseId) {
      try {
        const caseData = await base44.asServiceRole.entities.Case.filter({ id: caseId });
        if (caseData && caseData.length > 0) {
          const existingCase = caseData[0];

          // OWNERSHIP CHECK: caller must own the case (or be admin/ops)
          const role = (user.role || user.access_level || '').toLowerCase();
          const isAdminLike = ['admin', 'super_admin', 'va'].includes(role);
          if (!isAdminLike && existingCase.user_email !== user.email && existingCase.created_by !== user.email) {
            return Response.json({ ok: false, error: 'Forbidden: not your case' }, { status: 403 });
          }

          const existingLetters = existingCase.letters || {};

          existingLetters[`${subject}_url`] = docUrl;
          existingLetters[`${subject}_html_url`] = htmlUrl;

          const updatedTimeline = existingCase.timeline || [];
          updatedTimeline.push({
            timestamp: new Date().toISOString(),
            event: `letter_saved_${subject}`,
            actor: user.email,
            meta: { html_url: htmlUrl, doc_url: docUrl, document_id: docEntry.id, reviewed: true }
          });

          await base44.asServiceRole.entities.Case.update(caseId, {
            letters: existingLetters,
            timeline: updatedTimeline,
            status: 'ready_for_review'
          });
        }
      } catch (caseError) {
        console.error(`Failed to update case ${caseId}:`, caseError);
      }
    }

    return Response.json({
      ok: true,
      urls: { html: htmlUrl, doc: docUrl },
      docId: docEntry.id,
      case: caseId ? {
        id: caseId,
        status: 'ready_for_review'
      } : null
    });

  } catch (error) {
    console.error('Save reviewed letter error:', error);
    return Response.json({
      ok: false,
      error: error.message
    }, { status: 500 });
  }
});