const accountStrings = {
  en: {
    pageTitle: "My Account",
    pageSubtitle: "Manage your profile and subscription",
    personalInfo: "Personal Information",
    editProfile: "Edit Profile",
    fullName: "Full Name",
    email: "Email",
    cannotChange: "Cannot be changed",
    phone: "Phone Number",
    phonePlaceholder: "+66 XX XXX XXXX",
    country: "Country",
    countryPlaceholder: "Thailand",
    language: "Language",
    theme: "Theme",
    lightMode: "Light Mode",
    lightModeShort: "Light",
    darkMode: "Dark Mode",
    darkModeShort: "Dark",
    tenantAddress: "Your Address",
    tenantAddressPlaceholder: "Street address",
    tenantCity: "City",
    tenantCityPlaceholder: "Bangkok",
    tenantState: "State/Province",
    tenantStatePlaceholder: "Bangkok",
    tenantZip: "Postal Code",
    tenantZipPlaceholder: "10110",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    currentPlan: "Current Plan",
    billedMonthly: "Billed monthly",
    billedAnnually: "Billed annually",
    renews: "Renews",
    freePlanName: "Free",
    freeIncludes: "Free Plan Includes:",
    freeBenefit1: "1 Lease Scan (lifetime)",
    freeBenefit2: "Basic Risk Score Preview",
    freeBenefit3: "3 Files (100MB storage)",
    freeBenefit4: "Read-only Deposit Tracker",
    upgradeNow: "Upgrade Now",
    allActive: "All features active",
    lineEnabled: "LINE reminders enabled",
    helpSupport: "Help & Support",
    helpDesc: "Need assistance? Submit a request and we'll respond via email",
    submitRequest: "Submit Support Request",
    submitDesc: "Report issues, ask questions, or get help",
    directEmail: "Direct Email",
    responseTime: "Response within 2-3 business days",
    dataPrivacy: "Data Privacy & Your Rights",
    privacyPolicy: "Privacy Policy",
    privacyDesc: "Learn how we protect your data",
    viewPolicy: "View Policy",
    exportData: "Export My Data",
    exportDesc: "Download all your personal data (PDPA compliant)",
    export: "Export",
    exporting: "Exporting...",
    deleteAccount: "Need to Delete Your Account?",
    deleteDesc: "To request permanent deletion of your account and data, please email us from your registered email at",
    deleteNote: "After verification, your data will be deleted within 14 days, except where we must keep certain records for legal or accounting reasons.",
    preventionBannerTitle: "Prevention-First Protection",
    preventionBannerSubtitle: "Subscription-based protection for your lease, deposit, and documentation",
    preventionBannerText: "Lease Shield helps you maintain clear, legal, and evidence-based leasing relationships. Prevent rental problems before they happen with automated alerts, risk analysis, and professional templates.",
    monthly: "Monthly",
    annual: "Annual",
    save17: "Save 17%",
    notificationPreferences: "Notification Preferences",
    notificationInsights: "Notification Insights",
    choosePlan: "Choose Your Protection Level",
    planDesc: "All plans focus on prevention and maintaining clear records",
    mostPopular: "MOST POPULAR",
    monthsFree: "2 MONTHS FREE",
    noCreditCard: "No credit card required",
    perMonth: "/month",
    save: "Save",
    currentPlanBadge: "Current Plan",
    signupFree: "Sign Up to Get Free",
    startPlan: "Start",
    processing: "Processing...",
    monthlyBillingAvailable: "Monthly billing available at checkout",
    save17OnLite: "Save 17% on Lite",
    save17OnProtect: "Save 17% on Protect",
    save17OnSecure: "Save 17% on Secure",
    discountSubtext: "17% OFF — paid annually",
    logout: "Logout",
    notProvided: "Not provided",
    manageSubscription: "Manage Subscription",
    renewsOn: "Renews on",
    cancelPlan: "Change or Cancel Plan",
    cancelDialogTitle: "Cancel Your Subscription?",
    cancelDialogDesc: "We're sorry to see you go. Help us improve by telling us why you're leaving.",
    cancelReason: "Reason for Cancellation",
    selectReason: "Select a reason",
    reasonTooExpensive: "Too expensive",
    reasonNotUsingEnough: "Not using it enough",
    reasonFoundAlternative: "Found a better alternative",
    reasonMissingFeatures: "Missing features I need",
    reasonTechnicalIssues: "Technical issues",
    reasonOther: "Other",
    additionalFeedback: "Additional Feedback (Optional)",
    feedbackPlaceholder: "Help us understand what we could do better...",
    keepSubscription: "Keep My Subscription",
    confirmCancel: "Confirm Cancellation",
    cancelling: "Processing...",
    whatYoullLose: "What you'll lose",
    downgradeNote: "Your subscription will remain active until {date}. After that, you'll be downgraded to the Free plan.",
    scheduledCancellation: "Scheduled for Cancellation",
    cancelScheduledFor: "Cancels on",
    reactivate: "Reactivate Subscription",
    landlordInfo: "Landlord Information",
    landlordInfoDesc: "Store your landlord's contact details for quick notifications",
    landlordName: "Landlord Name",
    landlordEmail: "Landlord Email",
    landlordPhone: "Landlord Phone (WhatsApp)",
    landlordLine: "Landlord LINE ID",
    landlordAddress: "Landlord Address",
    juristicInfo: "Juristic Office Contact",
    juristicInfoDesc: "Store juristic office details for maintenance notifications",
    juristicName: "Contact Name",
    juristicEmail: "Email",
    juristicPhone: "Phone (WhatsApp)",
    juristicLine: "LINE ID",
    saveContactInfo: "Save Contact Info",
    connectLineOA: "Connect to LINE OA",
    connectLineOADesc: "Share this link to add them to Lease Shield notifications",
    copyLink: "Copy Link",
    shareLink: "Share Link",
    linkCopied: "Link Copied!",
    orManualEntry: "Or enter LINE ID manually",
    landlordLineConnect: "Connect Landlord to LINE",
    juristicLineConnect: "Connect Juristic to LINE",
    showQR: "Show QR Code",
    hideQR: "Hide QR Code",
    scanQR: "Scan this QR code with LINE app",
    buyCredits: "Buy Letter Credits",
    creditBalance: "Credit Balance",
    credits: "Credits",
    perCredit: "per credit",
    buyNow: "Buy Now",
    bestValue: "Best Value",
    creditPacks: "Credit Packs",
    oneLetterPerCredit: "1 letter = 1 credit",
    accessTemplateLibrary: "Access template library",
    bilingual: "Bilingual Templates",
    humanAndAiGeneration: "Human and AI generation",
    creditsNeverExpire: "Credits never expire",
    purchaseCredits: "Purchase Credits",
    currentPlanFree: "Current plan: Free",
    freeUpgradeText: "You're on basic coverage. Upgrade to Lite, Protect, or Secure for full deposit and maintenance protection.",
    chooseBillingInterval: "Choose Billing Cycle",
    payMonthly: "Pay Monthly",
    payAnnually: "Pay Annually",
    annualSavings: "Save 17% annually",
    bestValueBadge: "Best Value",
    proceedToCheckout: "Proceed to Checkout",
    upgradeToSecure: "Upgrade to Secure",
    unlockPremium: "Unlock Premium Features",
    secureFeatures: "50 scans/year, priority support & 50 letter credits/year",
    managementOptions: "Management options",
    managePlan: "Manage Plan",
    downgradeToFree: "Downgrade to Free",
    keepProtectionActive: "Keep your protection active?",
    retentionCopy: "You'll lose important protections if you downgrade. You can switch to a lower-cost plan instead.",
    switchToLite: "Switch to Lite",
    continueToFree: "Continue to Free plan",
    confirmDowngradeTitle: "Downgrade to Free plan",
    confirmDowngradeWarning: "You'll lose Unlimited Lease Scans, Advanced Reminders, extra Letter Credits and other premium protections.",
    reasonForDowngrade: "Reason for downgrading",
    goBack: "Go back",
    confirmDowngradeBtn: "Confirm downgrade to Free",
    saving: "Saving...",
    namePlaceholder: "Your full name",
    landlordNamePlaceholder: "Landlord name",
    landlordAddressPlaceholder: "Landlord address",
    juristicNamePlaceholder: "Contact name",
    appAndSharing: "App & Sharing",
    userManualTitle: "Lease Shield User Manual",
    userManualDesc: "Download complete guide (DOCX)",
    userManualDownloaded: "User manual downloaded",
    userManualFailed: "Failed to download manual",
    installAppTitle: "Install Lease Shield App",
    installAppDesc: "Add to home screen for quick access",
    shareAppTitle: "Share App with Friends",
    shareAppDesc: "Invite others to protect their deposits",
    deleteAccountTitle: "Delete Account Permanently",
    deleteAccountDesc: "Permanently delete all your data and account. This action cannot be undone.",
    dataAndStorage: "Data & Storage",
    recycleBin: "Recycle Bin",
    manageDeletedItems: "Manage deleted items",
    explorerAccount: "Explorer Account",
    exploringFeatures: "Exploring Features",
    exploringDesc: "You're exploring with a preview account. Upgrade to Lite, Protect, or Secure for full deposit and maintenance protection.",
    oneTimeScan: "One-Time Lease Scan",
    oneTimeLabel: "One-time",
    oneTimePayment: "(one-time payment)",
    oneTimeUpload: "1 upload + AI scan",
    oneTimeReview: "1 human-reviewed summary",
    oneTimeRisk: "Risk rating 1-100",
    oneTimeTop5: "Top 5 risk highlights",
    oneTimeActions: "5 recommended actions",
    oneTimeLetter: "1 letter template (if needed)",
    oneTimeFollowup: "1 follow-up clarification",
    oneTimeNote: "No subscription. No reminders. No storage.",
    buyOneTimeScan: "Get One-Time Scan",
    premiumBadge: "PREMIUM",
    installInstructions: "How to install",
    iosInstructions: "On iPhone/iPad:\n1. Tap Share button in Safari\n2. Tap 'Add to Home Screen'\n3. Tap 'Add'",
    androidInstructions: "On Android:\n1. Tap menu (⋮) in Chrome\n2. Tap 'Add to Home Screen'\n3. Tap 'Add'",
    desktopInstructions: "On Desktop:\n1. Click install icon in address bar\n2. Or use browser menu > 'Install Lease Shield'",
    gotIt: "Got it",
    install: "Install",
    alreadyInstalled: "Already installed",
    comingSoon: "Coming Soon",
    exportDialogData: "Data to be exported: profile, properties, evidence files, deposit tracking, cases, and notification settings",
    formatLabel: "Format:",
    lineAvailable: "LINE reminders available",
    thinkingDowngrade: "Thinking about downgrading?",
    downgradeRemovesTools: "Downgrading removes key protection tools and increases your risk.",
    youWillLose: "You will lose:",
    advancedReminders: "Advanced deadline reminders",
    fullTracking: "Full deposit & maintenance tracking",
    priorityCaseSupport: "Priority case support",
    additionalScans: "Additional lease scans",
    weakensProtection: "This weakens your protection. Stay on your current plan to keep your rights fully defended.",
    keepMyProtection: "Keep My Protection",
    downgradeAnyway: "Downgrade Anyway",
    liteBestFit: "- Best fit for most",
    litePriceDesc: "Only ฿190/month - keep core protections and save 81% from current plan",
    liteScanBenefit: "6 Lease Scans/year",
    liteEmailBenefit: "Email Notifications",
    liteTrackingBenefit: "Deposit & Maintenance Tracking",
    signUpToExplore: "Sign Up to Explore",
    cancelNeedTo: "Need to cancel your subscription?",
    manageOrCancel: "Manage or cancel subscription",
    upgradeSmarter: "Upgrade Smarter. Save 17%. Annual billing locks in your protection for the year and reduces monthly admin.",
    equivalent: "Equivalent to",
    shareAppText: "Prevent rental problems with Lease Shield - analyze contracts, track deposits, open cases easily",
    shared: "Shared!",
    linkCopiedShort: "Link copied!",
    failedToCopy: "Failed to copy",
    fileSaved: "File saved to Downloads",
    fileShared: "File shared successfully",
    installingApp: "Installing app...",
    exportFailed: "Failed to export data. Please try again.",
    myLeaseShieldData: "My Lease Shield Data",
    pricingUnavailable: "Pricing temporarily unavailable",
    tempUnavailable: "Temporarily Unavailable",
    checkoutFailed: "Failed to create checkout. Please try again.",
    subscriptionFailed: "Failed to start subscription"
  },
  th: {
    pageTitle: "บัญชีของฉัน",
    pageSubtitle: "จัดการโปรไฟล์และการสมัครสมาชิก",
    personalInfo: "ข้อมูลส่วนตัว",
    editProfile: "แก้ไขโปรไฟล์",
    fullName: "ชื่อ-นามสกุล",
    email: "อีเมล",
    cannotChange: "ไม่สามารถเปลี่ยนแปลงได้",
    phone: "เบอร์โทรศัพท์",
    phonePlaceholder: "+66 XX XXX XXXX",
    country: "ประเทศ",
    countryPlaceholder: "ประเทศไทย",
    language: "ภาษา",
    theme: "ธีม",
    lightMode: "โหมดสว่าง",
    lightModeShort: "สว่าง",
    darkMode: "โหมดมืด",
    darkModeShort: "มืด",
    tenantAddress: "ที่อยู่ของคุณ",
    tenantAddressPlaceholder: "ที่อยู่",
    tenantCity: "เมือง",
    tenantCityPlaceholder: "กรุงเทพฯ",
    tenantState: "จังหวัด",
    tenantStatePlaceholder: "กรุงเทพฯ",
    tenantZip: "รหัสไปรษณีย์",
    tenantZipPlaceholder: "10110",
    saveChanges: "บันทึกการเปลี่ยนแปลง",
    cancel: "ยกเลิก",
    currentPlan: "แผนปัจจุบัน",
    billedMonthly: "เรียกเก็บรายเดือน",
    billedAnnually: "เรียกเก็บรายปี",
    renews: "ต่ออายุ",
    freePlanName: "ฟรี",
    freeIncludes: "แผนฟรีประกอบด้วย:",
    freeBenefit1: "สแกนสัญญาเช่า 1 ครั้ง (ตลอดชีพ)",
    freeBenefit2: "ดูคะแนนความเสี่ยงเบื้องต้น",
    freeBenefit3: "3 ไฟล์ (พื้นที่ 100MB)",
    freeBenefit4: "เครื่องมือติดตามเงินมัดจำแบบอ่านอย่างเดียว",
    upgradeNow: "อัปเกรดเลย",
    allActive: "ฟีเจอร์ทั้งหมดใช้งานได้",
    lineEnabled: "การแจ้งเตือน LINE เปิดใช้งาน",
    helpSupport: "ช่วยเหลือและการสนับสนุน",
    helpDesc: "ต้องการความช่วยเหลือ? ส่งคำขอและเราจะตอบกลับทางอีเมล",
    submitRequest: "ส่งคำขอช่วยเหลือ",
    submitDesc: "รายงานปัญหา ถามคำถาม หรือขอความช่วยเหลือ",
    directEmail: "อีเมลโดยตรง",
    responseTime: "ตอบกลับภายใน 2-3 วันทำการ",
    dataPrivacy: "ความเป็นส่วนตัวของข้อมูลและสิทธิ์ของคุณ",
    privacyPolicy: "นโยบายความเป็นส่วนตัว",
    privacyDesc: "เรียนรู้วิธีที่เราปกป้องข้อมูลของคุณ",
    viewPolicy: "ดูนโยบาย",
    exportData: "ส่งออกข้อมูลของฉัน",
    exportDesc: "ดาวน์โหลดข้อมูลส่วนบุคคลทั้งหมด (ตาม พ.ร.บ. PDPA)",
    export: "ส่งออก",
    exporting: "กำลังส่งออก...",
    deleteAccount: "ต้องการลบบัญชี?",
    deleteDesc: "หากต้องการขอลบบัญชีและข้อมูลของคุณอย่างถาวร กรุณาส่งอีเมลจากอีเมลที่ลงทะเบียนไปที่",
    deleteNote: "หลังจากตรวจสอบแล้ว ข้อมูลของคุณจะถูกลบภายใน 14 วัน ยกเว้นกรณีที่เราต้องเก็บบันทึกบางอย่างตามกฎหมายหรือเพื่อการบัญชี",
    preventionBannerTitle: "การป้องกันเป็นอันดับแรก",
    preventionBannerSubtitle: "การป้องกันแบบสมัครสมาชิกสำหรับสัญญาเช่า เงินมัดจำ และเอกสารของคุณ",
    preventionBannerText: "Lease Shield ช่วยให้คุณรักษาความสัมพันธ์ในการเช่าที่ชัดเจน ถูกกฎหมาย และมีหลักฐาน ป้องกันปัญหาการเช่าก่อนที่จะเกิดขึ้นด้วยการแจ้งเตือนอัตโนมัติ การวิเคราะห์ความเสี่ยง และเทมเพลตมืออาชีพ",
    monthly: "รายเดือน",
    annual: "รายปี",
    save17: "ประหยัด 17%",
    notificationPreferences: "การตั้งค่าการแจ้งเตือน",
    notificationInsights: "สถิติการแจ้งเตือน",
    choosePlan: "เลือกระดับการป้องกันของคุณ",
    planDesc: "แผนทั้งหมดมุ่งเน้นการป้องกันและรักษาบันทึกที่ชัดเจน",
    mostPopular: "ได้รับความนิยมมากที่สุด",
    monthsFree: "ฟรี 2 เดือน",
    noCreditCard: "ไม่ต้องใช้บัตรเครดิต",
    perMonth: "/เดือน",
    save: "ประหยัด",
    currentPlanBadge: "แผนปัจจุบัน",
    signupFree: "สมัครเพื่อรับฟรี",
    startPlan: "เริ่มต้น",
    processing: "กำลังดำเนินการ...",
    monthlyBillingAvailable: "สามารถเลือกชำระรายเดือนได้ตอนชำระเงิน",
    save17OnLite: "ประหยัด 17% กับ Lite",
    save17OnProtect: "ประหยัด 17% กับ Protect",
    save17OnSecure: "ประหยัด 17% กับ Secure",
    discountSubtext: "17% OFF — ชำระรายปี",
    logout: "ออกจากระบบ",
    notProvided: "ไม่ได้ระบุ",
    manageSubscription: "จัดการการสมัครสมาชิก",
    renewsOn: "ต่ออายุเมื่อ",
    cancelPlan: "เปลี่ยนแปลงหรือยกเลิกแผน",
    cancelDialogTitle: "ยกเลิกการสมัครสมาชิก?",
    cancelDialogDesc: "เราเสียใจที่เห็นคุณจากไป ช่วยบอกเราว่าทำไมคุณถึงออกไป",
    cancelReason: "เหตุผลในการยกเลิก",
    selectReason: "เลือกเหตุผล",
    reasonTooExpensive: "แพงเกินไป",
    reasonNotUsingEnough: "ไม่ได้ใช้บ่อยพอ",
    reasonFoundAlternative: "พบทางเลือกที่ดีกว่า",
    reasonMissingFeatures: "ขาดฟีเจอร์ที่ต้องการ",
    reasonTechnicalIssues: "มีปัญหาทางเทคนิค",
    reasonOther: "อื่นๆ",
    additionalFeedback: "ข้อเสนอแนะเพิ่มเติม (ไม่บังคับ)",
    feedbackPlaceholder: "ช่วยบอกเราว่าเราสามารถทำอะไรได้ดีขึ้น...",
    keepSubscription: "เก็บการสมัครสมาชิกของฉันไว้",
    confirmCancel: "ยืนยันการยกเลิก",
    cancelling: "กำลังดำเนินการ...",
    whatYoullLose: "สิ่งที่คุณจะเสีย",
    downgradeNote: "การสมัครสมาชิกของคุณจะยังคงใช้งานได้จนถึง {date} หลังจากนั้นคุณจะถูกเปลี่ยนเป็นแผนฟรี",
    scheduledCancellation: "กำหนดการยกเลิกแล้ว",
    cancelScheduledFor: "จะยกเลิกเมื่อ",
    reactivate: "เปิดใช้งานการสมัครสมาชิกอีกครั้ง",
    landlordInfo: "ข้อมูลเจ้าของบ้าน",
    landlordInfoDesc: "เก็บข้อมูลติดต่อเจ้าของบ้านเพื่อการแจ้งเตือนอย่างรวดเร็ว",
    landlordName: "ชื่อเจ้าของบ้าน",
    landlordEmail: "อีเมลเจ้าของบ้าน",
    landlordPhone: "โทรศัพท์เจ้าของบ้าน (WhatsApp)",
    landlordLine: "LINE ID เจ้าของบ้าน",
    landlordAddress: "ที่อยู่เจ้าของบ้าน",
    juristicInfo: "ข้อมูลนิติบุคคล",
    juristicInfoDesc: "เก็บข้อมูลนิติบุคคลเพื่อการแจ้งเตือนการซ่อมบำรุง",
    juristicName: "ชื่อผู้ติดต่อ",
    juristicEmail: "อีเมล",
    juristicPhone: "โทรศัพท์ (WhatsApp)",
    juristicLine: "LINE ID",
    saveContactInfo: "บันทึกข้อมูลติดต่อ",
    connectLineOA: "เชื่อมต่อกับ LINE OA",
    connectLineOADesc: "แชร์ลิงก์นี้เพื่อเพิ่มพวกเขาในการแจ้งเตือน Lease Shield",
    copyLink: "คัดลอกลิงก์",
    shareLink: "แชร์ลิงก์",
    linkCopied: "คัดลอกลิงก์แล้ว!",
    orManualEntry: "หรือใส่ LINE ID ด้วยตนเอง",
    landlordLineConnect: "เชื่อมต่อเจ้าของบ้านกับ LINE",
    juristicLineConnect: "เชื่อมต่อนิติบุคคลกับ LINE",
    showQR: "แสดง QR Code",
    hideQR: "ซ่อน QR Code",
    scanQR: "สแกน QR Code นี้ด้วยแอป LINE",
    buyCredits: "ซื้อเครดิตจดหมาย",
    creditBalance: "เครดิตคงเหลือ",
    credits: "เครดิต",
    perCredit: "ต่อเครดิต",
    buyNow: "ซื้อเลย",
    bestValue: "คุ้มที่สุด",
    creditPacks: "แพ็กเกจเครดิต",
    oneLetterPerCredit: "1 จดหมาย = 1 เครดิต",
    accessTemplateLibrary: "เข้าถึงคลังเทมเพลต",
    bilingual: "เทมเพลตสองภาษา",
    humanAndAiGeneration: "สร้างโดยมนุษย์และ AI",
    creditsNeverExpire: "เครดิตไม่หมดอายุ",
    purchaseCredits: "ซื้อเครดิต",
    currentPlanFree: "แผนปัจจุบัน: ฟรี",
    freeUpgradeText: "คุณอยู่ในการคุ้มครองพื้นฐาน อัปเกรดเป็น Lite, Protect หรือ Secure เพื่อการป้องกันเงินมัดจำและการซ่อมบำรุงเต็มรูปแบบ",
    chooseBillingInterval: "เลือกรอบการเรียกเก็บเงิน",
    payMonthly: "ชำระรายเดือน",
    payAnnually: "ชำระรายปี",
    annualSavings: "ประหยัด 17% ต่อปี",
    bestValueBadge: "คุ้มค่าที่สุด",
    proceedToCheckout: "ไปที่การชำระเงิน",
    upgradeToSecure: "อัปเกรดเป็น Secure",
    unlockPremium: "ปลดล็อกฟีเจอร์พรีเมียม",
    secureFeatures: "50 สแกน/ปี การสนับสนุนลำดับความสำคัญ และ 50 เครดิตจดหมาย/ปี",
    managementOptions: "ตัวเลือกการจัดการ",
    managePlan: "จัดการแผน",
    downgradeToFree: "ลดเป็นฟรี",
    keepProtectionActive: "รักษาการป้องกันของคุณไว้?",
    retentionCopy: "คุณจะสูญเสียการป้องกันที่สำคัญหากคุณลดระดับ คุณสามารถเปลี่ยนเป็นแผนที่ถูกกว่าแทนได้",
    switchToLite: "เปลี่ยนเป็น Lite",
    continueToFree: "ดำเนินการไปยังแผนฟรี",
    confirmDowngradeTitle: "ลดเป็นแผนฟรี",
    confirmDowngradeWarning: "คุณจะสูญเสียการสแกนสัญญาไม่จำกัด การแจ้งเตือนขั้นสูง เครดิตจดหมายเพิ่มเติม และการป้องกันพรีเมียมอื่นๆ",
    reasonForDowngrade: "เหตุผลในการลดระดับ",
    goBack: "กลับ",
    confirmDowngradeBtn: "ยืนยันการลดเป็นฟรี",
    saving: "กำลังบันทึก...",
    namePlaceholder: "ชื่อ-นามสกุลของคุณ",
    landlordNamePlaceholder: "ชื่อเจ้าของบ้าน",
    landlordAddressPlaceholder: "ที่อยู่เจ้าของบ้าน",
    juristicNamePlaceholder: "ชื่อผู้ติดต่อ",
    appAndSharing: "แอปและการแชร์",
    userManualTitle: "คู่มือผู้ใช้ Lease Shield",
    userManualDesc: "ดาวน์โหลดคู่มือฉบับเต็ม (DOCX)",
    userManualDownloaded: "ดาวน์โหลดคู่มือผู้ใช้แล้ว",
    userManualFailed: "ไม่สามารถดาวน์โหลดคู่มือได้",
    installAppTitle: "ติดตั้งแอป Lease Shield",
    installAppDesc: "เพิ่มลงในหน้าจอหลักเพื่อเข้าถึงง่ายๆ",
    shareAppTitle: "แชร์แอปกับเพื่อน",
    shareAppDesc: "ชวนคนอื่นมาป้องกันเงินมัดจำของพวกเขา",
    deleteAccountTitle: "ลบบัญชีอย่างถาวร",
    deleteAccountDesc: "ลบข้อมูลทั้งหมดและบัญชีของคุณอย่างถาวร การกระทำนี้ไม่สามารถยกเลิกได้",
    dataAndStorage: "ข้อมูลและพื้นที่จัดเก็บ",
    recycleBin: "ถังขยะ",
    manageDeletedItems: "จัดการรายการที่ลบ",
    explorerAccount: "บัญชีสำรวจ",
    exploringFeatures: "กำลังสำรวจอยู่",
    exploringDesc: "คุณอยู่ในบัญชีสำรวจ อัปเกรดเป็น Lite, Protect หรือ Secure เพื่อการป้องกันเงินมัดจำและการซ่อมบำรุงเต็มรูปแบบ",
    oneTimeScan: "การสแกนสัญญาเช่าครั้งเดียว",
    oneTimeLabel: "ครั้งเดียว",
    oneTimePayment: "(ชำระครั้งเดียว)",
    oneTimeUpload: "อัปโหลด 1 ครั้ง + วิเคราะห์ด้วย AI",
    oneTimeReview: "สรุปโดยผู้เชี่ยวชาญ 1 ฉบับ",
    oneTimeRisk: "คะแนนความเสี่ยง 1-100",
    oneTimeTop5: "ความเสี่ยง 5 อันดับแรก",
    oneTimeActions: "ขั้นตอนแนะนำ 5 ข้อ",
    oneTimeLetter: "เทมเพลตจดหมาย 1 ฉบับ (ถ้าจำเป็น)",
    oneTimeFollowup: "ถามชี้แจงเพิ่มเติม 1 คำถาม",
    oneTimeNote: "ไม่มีการสมัครสมาชิก ไม่มีการแจ้งเตือนอัตโนมัติ ไม่มีพื้นที่จัดเก็บ",
    buyOneTimeScan: "ซื้อการสแกนครั้งเดียว",
    premiumBadge: "พรีเมียม",
    installInstructions: "วิธีติดตั้ง",
    iosInstructions: "บน iPhone/iPad:\n1. แตะปุ่มแชร์ใน Safari\n2. แตะ 'เพิ่มที่หน้าจอโฮม'\n3. แตะ 'เพิ่ม'",
    androidInstructions: "บน Android:\n1. แตะเมนู (⋮) ใน Chrome\n2. แตะ 'เพิ่มที่หน้าจอโฮม'\n3. แตะ 'เพิ่ม'",
    desktopInstructions: "บนเดสก์ท็อป:\n1. คลิกไอคอนติดตั้งในแถบที่อยู่\n2. หรือใช้เมนูเบราว์เซอร์ > 'ติดตั้ง Lease Shield'",
    gotIt: "เข้าใจแล้ว",
    install: "ติดตั้ง",
    alreadyInstalled: "ติดตั้งแล้ว",
    comingSoon: "เร็วๆ นี้",
    exportDialogData: "ข้อมูลที่จะถูกส่งออก: โปรไฟล์, ทรัพย์สิน, เอกสารหลักฐาน, การติดตามเงินมัดจำ, คดี และการตั้งค่าการแจ้งเตือน",
    formatLabel: "รูปแบบ:",
    lineAvailable: "การแจ้งเตือน LINE พร้อมใช้งาน",
    thinkingDowngrade: "กำลังคิดจะลดระดับ?",
    downgradeRemovesTools: "การลดระดับจะลบเครื่องมือป้องกันที่สำคัญและเพิ่มความเสี่ยงของคุณ",
    youWillLose: "คุณจะสูญเสีย:",
    advancedReminders: "การแจ้งเตือนกำหนดเวลาขั้นสูง",
    fullTracking: "การติดตามเงินมัดจำและการซ่อมบำรุงแบบเต็มรูปแบบ",
    priorityCaseSupport: "การสนับสนุนคดีลำดับความสำคัญ",
    additionalScans: "การสแกนสัญญาเพิ่มเติม",
    weakensProtection: "สิ่งนี้ทำให้การป้องกันของคุณอ่อนแอลง อยู่ในแผนปัจจุบันเพื่อรักษาสิทธิ์ของคุณให้ได้รับการป้องกันอย่างเต็มที่",
    keepMyProtection: "รักษาการป้องกันของฉัน",
    downgradeAnyway: "ลดระดับต่อไป",
    liteBestFit: "- แผนที่เหมาะสมที่สุด",
    litePriceDesc: "เพียง ฿190/เดือน - รักษาการป้องกันหลักและประหยัด 81% จากแผนปัจจุบัน",
    liteScanBenefit: "6 การสแกนสัญญาต่อปี",
    liteEmailBenefit: "การแจ้งเตือนทางอีเมล",
    liteTrackingBenefit: "ติดตามเงินมัดจำและการซ่อมบำรุง",
    signUpToExplore: "ลงทะเบียนเพื่อสำรวจ",
    cancelNeedTo: "ต้องการยกเลิกการสมัครสมาชิก?",
    manageOrCancel: "จัดการหรือยกเลิกการสมัครสมาชิก",
    upgradeSmarter: "อัปเกรดอย่างชาญฉลาด ประหยัด 17% การเรียกเก็บรายปีช่วยรักษาการป้องกันของคุณตลอดปีและลดการจัดการรายเดือน",
    equivalent: "เท่ากับ",
    shareAppText: "ป้องกันปัญหาการเช่าด้วย Lease Shield - วิเคราะห์สัญญา ติดตามเงินมัดจำ และเปิดคดีได้ง่ายๆ",
    shared: "แชร์แล้ว!",
    linkCopiedShort: "คัดลอกลินก์แล้ว!",
    failedToCopy: "ไม่สามารถคัดลอกได้",
    fileSaved: "บันทึกไฟล์แล้ว",
    fileShared: "แชร์ไฟล์สำเร็จ",
    installingApp: "กำลังติดตั้งแอป...",
    exportFailed: "ส่งออกล้มเหลว กรุณาลองอีกครั้ง",
    myLeaseShieldData: "ข้อมูล Lease Shield ของฉัน",
    pricingUnavailable: "ราคาไม่พร้อมใช้งานชั่วคราว",
    tempUnavailable: "ไม่พร้อมใช้งานชั่วคราว",
    checkoutFailed: "ไม่สามารถสร้างการชำระเงินได้ กรุณาลองอีกครั้ง",
    subscriptionFailed: "ไม่สามารถสร้างการสมัครได้"
  },
  zh: {
    pageTitle: "我的账户", pageSubtitle: "管理您的个人资料和订阅", personalInfo: "个人信息", editProfile: "编辑个人资料", fullName: "全名", email: "电子邮件", cannotChange: "无法更改", phone: "电话号码", phonePlaceholder: "+66 XX XXX XXXX", country: "国家", countryPlaceholder: "泰国", language: "语言", theme: "主题", lightMode: "浅色模式", lightModeShort: "浅色", darkMode: "深色模式", darkModeShort: "深色", tenantAddress: "您的地址", tenantAddressPlaceholder: "街道地址", tenantCity: "城市", tenantCityPlaceholder: "曼谷", tenantState: "州/省", tenantStatePlaceholder: "曼谷", tenantZip: "邮政编码", tenantZipPlaceholder: "10110", saveChanges: "保存更改", cancel: "取消", currentPlan: "当前计划", billedMonthly: "按月计费", billedAnnually: "按年计费", renews: "续订", freePlanName: "免费", freeIncludes: "免费计划包括：", freeBenefit1: "1次租约扫描（终身）", freeBenefit2: "基本风险评分预览", freeBenefit3: "3个文件（100MB存储）", freeBenefit4: "只读押金追踪器", upgradeNow: "立即升级", allActive: "所有功能已激活", lineEnabled: "LINE提醒已启用", helpSupport: "帮助与支持", helpDesc: "需要帮助？提交请求，我们将通过电子邮件回复", submitRequest: "提交支持请求", submitDesc: "报告问题、提问或获取帮助", directEmail: "直接电子邮件", responseTime: "2-3个工作日内回复", dataPrivacy: "数据隐私与您的权利", privacyPolicy: "隐私政策", privacyDesc: "了解我们如何保护您的数据", viewPolicy: "查看政策", exportData: "导出我的数据", exportDesc: "下载您的所有个人数据（符合PDPA）", export: "导出", exporting: "导出中...", deleteAccount: "需要删除您的账户？", deleteDesc: "要请求永久删除您的账户和数据，请从您注册的电子邮件向我们发送邮件至", deleteNote: "验证后，您的数据将在14天内删除，除非我们必须出于法律或会计原因保留某些记录。", preventionBannerTitle: "预防优先保护", preventionBannerSubtitle: "基于订阅的租约、押金和文档保护", preventionBannerText: "Lease Shield帮助您维护清晰、合法且基于证据的租赁关系。通过自动提醒、风险分析和专业模板，在问题发生前预防租赁问题。", monthly: "按月", annual: "按年", save17: "节省17%", notificationPreferences: "通知偏好", notificationInsights: "通知统计", choosePlan: "选择您的保护级别", planDesc: "所有计划都专注于预防和维护清晰的记录", mostPopular: "最受欢迎", monthsFree: "免费2个月", noCreditCard: "无需信用卡", perMonth: "/月", save: "节省", currentPlanBadge: "当前计划", signupFree: "注册获取免费", startPlan: "开始", processing: "处理中...", monthlyBillingAvailable: "结账时可选择按月计费", save17OnLite: "Lite 省 17%", save17OnProtect: "Protect 省 17%", save17OnSecure: "Secure 省 17%", discountSubtext: "17% 折扣 — 按年支付", logout: "登出", notProvided: "未提供", manageSubscription: "管理订阅", renewsOn: "续订日期", cancelPlan: "更改或取消计划", cancelDialogTitle: "取消您的订阅？", cancelDialogDesc: "很遗憾看到您离开。请告诉我们您离开的原因以帮助我们改进。", cancelReason: "取消原因", selectReason: "选择原因", reasonTooExpensive: "太贵了", reasonNotUsingEnough: "使用不够频繁", reasonFoundAlternative: "找到了更好的替代品", reasonMissingFeatures: "缺少我需要的功能", reasonTechnicalIssues: "技术问题", reasonOther: "其他", additionalFeedback: "其他反馈（可选）", feedbackPlaceholder: "帮助我们了解我们可以做得更好...", keepSubscription: "保留我的订阅", confirmCancel: "确认取消", cancelling: "处理中...", whatYoullLose: "您将失去的内容", downgradeNote: "您的订阅将保持活动状态直到{date}。之后，您将降级到免费计划。", scheduledCancellation: "计划取消", cancelScheduledFor: "取消日期", reactivate: "重新激活订阅", landlordInfo: "房东信息", landlordInfoDesc: "存储房东的联系方式以便快速通知", landlordName: "房东姓名", landlordEmail: "房东电子邮件", landlordPhone: "房东电话（WhatsApp）", landlordLine: "房东LINE ID", landlordAddress: "房东地址", juristicInfo: "物业办公室联系方式", juristicInfoDesc: "存储物业办公室详细信息以接收维护通知", juristicName: "联系人姓名", juristicEmail: "电子邮件", juristicPhone: "电话（WhatsApp）", juristicLine: "LINE ID", saveContactInfo: "保存联系信息", connectLineOA: "连接到LINE OA", connectLineOADesc: "分享此链接以将他们添加到Lease Shield通知", copyLink: "复制链接", shareLink: "分享链接", linkCopied: "链接已复制！", orManualEntry: "或手动输入LINE ID", landlordLineConnect: "将房东连接到LINE", juristicLineConnect: "将物业连接到LINE", showQR: "显示二维码", hideQR: "隐藏二维码", scanQR: "使用LINE应用扫描此二维码", buyCredits: "购买信件积分", creditBalance: "积分余额", credits: "积分", perCredit: "每积分", buyNow: "立即购买", bestValue: "最佳价值", creditPacks: "积分套餐", oneLetterPerCredit: "1封信件 = 1积分", accessTemplateLibrary: "访问模板库", bilingual: "双语模板", humanAndAiGeneration: "人工和AI生成", creditsNeverExpire: "积分永不过期", purchaseCredits: "购买积分", currentPlanFree: "当前计划: 免费", freeUpgradeText: "您目前使用的是基本保障。升级到 Lite、Protect 或 Secure 方案，即可获得完整的押金和维护保障。", chooseBillingInterval: "选择计费周期", payMonthly: "按月支付", payAnnually: "按年支付", annualSavings: "每年节省17%", bestValueBadge: "最划算", proceedToCheckout: "前往结账", upgradeToSecure: "升级到Secure", unlockPremium: "解锁高级功能", secureFeatures: "每年50次扫描，优先支持和每年50个信件积分", managementOptions: "管理选项", managePlan: "管理计划", downgradeToFree: "降级到免费", keepProtectionActive: "保持您的保护活跃吗？", retentionCopy: "如果您降级，您将失去重要的保护。您可以改为切换到更低成本的计划。", switchToLite: "切换到Lite", continueToFree: "继续到免费计划", confirmDowngradeTitle: "降级到免费计划", confirmDowngradeWarning: "您将失去无限次租约扫描、高级提醒、额外信件积分和其他高级保护。", reasonForDowngrade: "降级原因", goBack: "返回", confirmDowngradeBtn: "确认降级到免费",
    saving: "保存中...", namePlaceholder: "您的全名", landlordNamePlaceholder: "房东姓名", landlordAddressPlaceholder: "房东地址", juristicNamePlaceholder: "联系人姓名", appAndSharing: "应用与分享", userManualTitle: "Lease Shield 用户手册", userManualDesc: "下载完整手册 (DOCX)", userManualDownloaded: "用户手册已下载", userManualFailed: "无法下载手册", installAppTitle: "安装 Lease Shield 应用", installAppDesc: "添加到主屏幕以便快速访问", shareAppTitle: "与朋友分享应用", shareAppDesc: "邀请他人保护他们的押金", deleteAccountTitle: "永久删除账户", deleteAccountDesc: "永久删除您的所有数据和账户。此操作无法撤销。", dataAndStorage: "数据与存储", recycleBin: "回收站", manageDeletedItems: "管理已删除项目", explorerAccount: "探索账户", exploringFeatures: "当前探索中", exploringDesc: "您正在使用探索账户。升级到 Lite、Protect 或 Secure 以获得完整的押金和维护保护。",
    oneTimeScan: "一次性租约扫描", oneTimeLabel: "一次性", oneTimePayment: "(一次性付款)", oneTimeUpload: "1次上传 + AI分析", oneTimeReview: "1份专家审核摘要", oneTimeRisk: "风险评分1-100", oneTimeTop5: "前5大风险", oneTimeActions: "5项建议行动", oneTimeLetter: "1个信件模板（如需）", oneTimeFollowup: "1次后续澄清问题", oneTimeNote: "无订阅，无自动提醒，无存储空间", buyOneTimeScan: "购买一次性扫描", premiumBadge: "高级版",
    installInstructions: "安装说明", iosInstructions: "在 iPhone/iPad 上:\n1. 在 Safari 中点击分享按钮\n2. 点击'添加到主屏幕'\n3. 点击'添加'", androidInstructions: "在 Android 上:\n1. 在 Chrome 中点击菜单 (⋮)\n2. 点击'添加到主屏幕'\n3. 点击'添加'", desktopInstructions: "在桌面上:\n1. 点击地址栏中的安装图标\n2. 或使用浏览器菜单 > '安装 Lease Shield'", gotIt: "知道了", install: "安装", alreadyInstalled: "已安装", comingSoon: "即将推出",
    exportDialogData: "将导出的数据：个人资料、房产、证据文件、押金追踪、案件和通知设置", formatLabel: "格式：", lineAvailable: "LINE提醒可用",
    thinkingDowngrade: "考虑降级？", downgradeRemovesTools: "降级会删除关键保护工具并增加您的风险。", youWillLose: "您将失去：", advancedReminders: "高级截止日期提醒", fullTracking: "完整押金和维护追踪", priorityCaseSupport: "优先案件支持", additionalScans: "额外租约扫描", weakensProtection: "这会削弱您的保护。保持当前计划以全面保护您的权利。", keepMyProtection: "保持我的保护", downgradeAnyway: "继续降级",
    liteBestFit: "- 最适合大多数人", litePriceDesc: "仅฿190/月 - 保持核心保护并比当前计划节省81%", liteScanBenefit: "每年6次租约扫描", liteEmailBenefit: "电子邮件通知", liteTrackingBenefit: "押金和维护追踪", signUpToExplore: "注册探索", cancelNeedTo: "需要取消订阅吗？", manageOrCancel: "管理或取消订阅", upgradeSmarter: "更智能升级。节省17%。年度计费锁定全年保护并减少每月管理。", equivalent: "相当于",
    shareAppText: "用 Lease Shield 防止租赁问题 - 分析合同、追踪押金、轻松开案", shared: "已分享！", linkCopiedShort: "链接已复制！", failedToCopy: "无法复制", fileSaved: "文件已保存", fileShared: "文件分享成功", installingApp: "正在安装应用...", exportFailed: "导出失败，请重试", myLeaseShieldData: "我的 Lease Shield 数据", pricingUnavailable: "价格暂时不可用", tempUnavailable: "暂时不可用", checkoutFailed: "无法创建付款，请重试", subscriptionFailed: "无法创建订阅"
  },
  ja: {
    pageTitle: "マイアカウント", pageSubtitle: "プロフィールとサブスクリプションを管理", personalInfo: "個人情報", editProfile: "プロフィールを編集", fullName: "フルネーム", email: "メールアドレス", cannotChange: "変更できません", phone: "電話番号", phonePlaceholder: "+66 XX XXX XXXX", country: "国", countryPlaceholder: "タイ", language: "言語", theme: "テーマ", lightMode: "ライトモード", lightModeShort: "ライト", darkMode: "ダークモード", darkModeShort: "ダーク", tenantAddress: "あなたの住所", tenantAddressPlaceholder: "住所", tenantCity: "市", tenantCityPlaceholder: "バンコク", tenantState: "州/県", tenantStatePlaceholder: "バンコク", tenantZip: "郵便番号", tenantZipPlaceholder: "10110", saveChanges: "変更を保存", cancel: "キャンセル", currentPlan: "現在のプラン", billedMonthly: "月額請求", billedAnnually: "年間請求", renews: "更新", freePlanName: "無料", freeIncludes: "無料プランに含まれるもの：", freeBenefit1: "1回の賃貸契約スキャン（生涯）", freeBenefit2: "基本リスクスコアプレビュー", freeBenefit3: "3ファイル（100MBストレージ）", freeBenefit4: "読み取り専用敷金トラッカー", upgradeNow: "今すぐアップグレード", allActive: "すべての機能が有効", lineEnabled: "LINEリマインダーが有効", helpSupport: "ヘルプとサポート", helpDesc: "サポートが必要ですか？リクエストを送信すると、メールで返信します", submitRequest: "サポートリクエストを送信", submitDesc: "問題を報告、質問、またはヘルプを取得", directEmail: "直接メール", responseTime: "2-3営業日以内に返信", dataPrivacy: "データプライバシーとあなたの権利", privacyPolicy: "プライバシーポリシー", privacyDesc: "データの保護方法を学ぶ", viewPolicy: "ポリシーを表示", exportData: "マイデータをエクスポート", exportDesc: "すべての個人データをダウンロード（PDPA準拠）", export: "エクスポート", exporting: "エクスポート中...", deleteAccount: "アカウントを削除する必要がありますか？", deleteDesc: "アカウントとデータの永久削除をリクエストするには、登録されたメールアドレスから次のアドレスにメールを送信してください", deleteNote: "確認後、法律または会計上の理由で特定の記録を保持する必要がある場合を除き、14日以内にデータが削除されます。", preventionBannerTitle: "予防第一の保護", preventionBannerSubtitle: "賃貸契約、敷金、文書のためのサブスクリプションベースの保護", preventionBannerText: "Lease Shieldは、明確で合法的かつ証拠に基づく賃貸関係の維持を支援します。自動アラート、リスク分析、プロフェッショナルテンプレートで賃貸問題を事前に防止します。", monthly: "月額", annual: "年額", save17: "17%節約", notificationPreferences: "通知設定", notificationInsights: "通知インサイト", choosePlan: "保護レベルを選択", planDesc: "すべてのプランは予防と明確な記録の維持に焦点を当てています", mostPopular: "最も人気", monthsFree: "2ヶ月無料", noCreditCard: "クレジットカード不要", perMonth: "/月", save: "節約", currentPlanBadge: "現在のプラン", signupFree: "無料でサインアップ", startPlan: "開始", processing: "処理中...", monthlyBillingAvailable: "月払いもチェックアウト時に選択可能", save17OnLite: "Lite で 17% 節約", save17OnProtect: "Protect で 17% 節約", save17OnSecure: "Secure で 17% 節約", discountSubtext: "17% OFF — 年払い", logout: "ログアウト", notProvided: "未提供", manageSubscription: "サブスクリプション管理", renewsOn: "更新日", cancelPlan: "プランを変更またはキャンセル", cancelDialogTitle: "サブスクリプションをキャンセルしますか？", cancelDialogDesc: "お別れするのは残念です。なぜ離れるのか教えてください。", cancelReason: "キャンセル理由", selectReason: "理由を選択", reasonTooExpensive: "高すぎる", reasonNotUsingEnough: "十分に使用していない", reasonFoundAlternative: "より良い代替品を見つけた", reasonMissingFeatures: "必要な機能がない", reasonTechnicalIssues: "技術的な問題", reasonOther: "その他", additionalFeedback: "追加のフィードバック（オプション）", feedbackPlaceholder: "改善できることを教えてください...", keepSubscription: "サブスクリプションを維持", confirmCancel: "キャンセルを確認", cancelling: "処理中...", whatYoullLose: "失うもの", downgradeNote: "サブスクリプションは{date}まで有効です。その後、無料プランにダウングレードされます。", scheduledCancellation: "キャンセル予定", cancelScheduledFor: "キャンセル日", reactivate: "サブスクリプションを再開", landlordInfo: "家主情報", landlordInfoDesc: "迅速な通知のために家主の連絡先を保存", landlordName: "家主名", landlordEmail: "家主メール", landlordPhone: "家主電話（WhatsApp）", landlordLine: "家主LINE ID", landlordAddress: "家主住所", juristicInfo: "管理事務所連絡先", juristicInfoDesc: "メンテナンス通知用に管理事務所の詳細を保存", juristicName: "連絡先名", juristicEmail: "メール", juristicPhone: "電話（WhatsApp）", juristicLine: "LINE ID", saveContactInfo: "連絡先情報を保存", connectLineOA: "LINE OAに接続", connectLineOADesc: "このリンクを共有してLease Shield通知に追加", copyLink: "リンクをコピー", shareLink: "リンクを共有", linkCopied: "リンクをコピーしました！", orManualEntry: "またはLINE IDを手動入力", landlordLineConnect: "家主をLINEに接続", juristicLineConnect: "管理事務所をLINEに接続", showQR: "QRコードを表示", hideQR: "QRコードを非表示", scanQR: "LINEアプリでこのQRコードをスキャン", buyCredits: "レタークレジットを購入", creditBalance: "クレジット残高", credits: "クレジット", perCredit: "クレジットあたり", buyNow: "今すぐ購入", bestValue: "最高の価値", creditPacks: "クレジットパック", oneLetterPerCredit: "1レター = 1クレジット", accessTemplateLibrary: "テンプレートライブラリにアクセス", bilingual: "バイリンガルテンプレート", humanAndAiGeneration: "人間とAIの生成", creditsNeverExpire: "クレジットは期限切れになりません", purchaseCredits: "クレジットを購入", currentPlanFree: "現在のプラン: 無料", freeUpgradeText: "あなたは基本的な補償を受けています。Lite、Protect、またはSecureにアップグレードしてください。", chooseBillingInterval: "請求サイクルを選択", payMonthly: "月払い", payAnnually: "年払い", annualSavings: "年間17%節約", bestValueBadge: "ベストバリュー", proceedToCheckout: "チェックアウトに進む", upgradeToSecure: "Secureにアップグレード", unlockPremium: "プレミアム機能のロックを解除", secureFeatures: "年50回スキャン、優先サポート、年50レタークレジット", managementOptions: "管理オプション", managePlan: "プラン管理", downgradeToFree: "無料プランにダウングレード", keepProtectionActive: "保護を継続しますか？", retentionCopy: "ダウングレードすると、重要な保護が失われます。代わりに低コストのプランに切り替えることもできます。", switchToLite: "Liteに切り替える", continueToFree: "無料プランに進む", confirmDowngradeTitle: "無料プランにダウングレード", confirmDowngradeWarning: "無制限のリーススキャン、高度なリマインダー、追加のレタークレジット、その他のプレミアム保護が失われます。", reasonForDowngrade: "ダウングレードの理由", goBack: "戻る", confirmDowngradeBtn: "無料プランへのダウングレードを確認",
    saving: "保存中...", namePlaceholder: "フルネーム", landlordNamePlaceholder: "家主名", landlordAddressPlaceholder: "家主住所", juristicNamePlaceholder: "連絡先名", appAndSharing: "アプリと共有", userManualTitle: "Lease Shield ユーザーマニュアル", userManualDesc: "完全版マニュアルをダウンロード (DOCX)", userManualDownloaded: "ユーザーマニュアルをダウンロードしました", userManualFailed: "マニュアルのダウンロードに失敗しました", installAppTitle: "Lease Shield アプリをインストール", installAppDesc: "ホーム画面に追加して素早くアクセス", shareAppTitle: "友達とアプリを共有", shareAppDesc: "他の人に敷金保護を勧める", deleteAccountTitle: "アカウントを完全に削除", deleteAccountDesc: "すべてのデータとアカウントを完全に削除します。この操作は元に戻せません。", dataAndStorage: "データとストレージ", recycleBin: "ゴミ箱", manageDeletedItems: "削除されたアイテムを管理", explorerAccount: "探索アカウント", exploringFeatures: "探索中", exploringDesc: "探索アカウントを使用中。完全な預金およびメンテナンス保護のために、Lite、Protect、またはSecureにアップグレードしてください。",
    oneTimeScan: "一回限りリーススキャン", oneTimeLabel: "一回限り", oneTimePayment: "(一回払い)", oneTimeUpload: "1アップロード + AI分析", oneTimeReview: "専門家による1件のレビュー", oneTimeRisk: "リスク評価1-100", oneTimeTop5: "トップ5リスク", oneTimeActions: "5つの推奨アクション", oneTimeLetter: "1レターテンプレート（必要時）", oneTimeFollowup: "1件のフォローアップ質問", oneTimeNote: "サブスクなし、自動リマインダーなし、ストレージなし", buyOneTimeScan: "一回スキャンを購入", premiumBadge: "プレミアム",
    installInstructions: "インストール方法", iosInstructions: "iPhone/iPadで:\n1. Safariで共有ボタンをタップ\n2. 「ホーム画面に追加」をタップ\n3. 「追加」をタップ", androidInstructions: "Androidで:\n1. Chromeでメニュー (⋮) をタップ\n2. 「ホーム画面に追加」をタップ\n3. 「追加」をタップ", desktopInstructions: "デスクトップで:\n1. アドレスバーのインストールアイコンをクリック\n2. またはブラウザメニュー > 「Lease Shieldをインストール」", gotIt: "了解", install: "インストール", alreadyInstalled: "インストール済み", comingSoon: "近日公開",
    exportDialogData: "エクスポートされるデータ：プロフィール、物件、証拠ファイル、敷金追跡、ケース、通知設定", formatLabel: "フォーマット：", lineAvailable: "LINEリマインダー利用可能",
    thinkingDowngrade: "ダウングレードを検討中？", downgradeRemovesTools: "ダウングレードすると、重要な保護ツールが削除され、リスクが高まります。", youWillLose: "失うもの：", advancedReminders: "高度な期限リマインダー", fullTracking: "完全な敷金とメンテナンス追跡", priorityCaseSupport: "優先ケースサポート", additionalScans: "追加リーススキャン", weakensProtection: "これにより保護が弱まります。現在のプランを維持して、権利を完全に守りましょう。", keepMyProtection: "私の保護を維持", downgradeAnyway: "ダウングレードを続行",
    liteBestFit: "- ほとんどの人に最適", litePriceDesc: "わずか฿190/月 - コア保護を維持し、現在のプランから81%節約", liteScanBenefit: "年6回のリーススキャン", liteEmailBenefit: "メール通知", liteTrackingBenefit: "敷金とメンテナンス追跡", signUpToExplore: "登録して探索", cancelNeedTo: "サブスクリプションをキャンセルする必要がありますか？", manageOrCancel: "サブスクリプションを管理またはキャンセル", upgradeSmarter: "よりスマートにアップグレード。17%節約。年間請求で1年間の保護をロックし、月次管理を削減。", equivalent: "同等",
    shareAppText: "Lease Shieldで賃貸問題を防ぐ - 契約分析、敷金追跡、簡単にケース開設", shared: "共有しました！", linkCopiedShort: "リンクをコピーしました！", failedToCopy: "コピーできませんでした", fileSaved: "ファイルを保存しました", fileShared: "ファイルを共有しました", installingApp: "アプリをインストール中...", exportFailed: "エクスポートに失敗しました。もう一度お試しください", myLeaseShieldData: "Lease Shieldデータ", pricingUnavailable: "価格は一時的に利用できません", tempUnavailable: "一時的に利用不可", checkoutFailed: "チェックアウトの作成に失敗しました。もう一度お試しください", subscriptionFailed: "サブスクリプションの開始に失敗しました"
  },
  ko: {
    pageTitle: "내 계정", pageSubtitle: "프로필 및 구독 관리", personalInfo: "개인 정보", editProfile: "프로필 편집", fullName: "전체 이름", email: "이메일", cannotChange: "변경할 수 없음", phone: "전화번호", phonePlaceholder: "+66 XX XXX XXXX", country: "국가", countryPlaceholder: "태국", language: "언어", theme: "테마", lightMode: "라이트 모드", lightModeShort: "라이트", darkMode: "다크 모드", darkModeShort: "다크", tenantAddress: "귀하의 주소", tenantAddressPlaceholder: "도로명 주소", tenantCity: "도시", tenantCityPlaceholder: "방콕", tenantState: "주/도", tenantStatePlaceholder: "방콕", tenantZip: "우편번호", tenantZipPlaceholder: "10110", saveChanges: "변경 사항 저장", cancel: "취소", currentPlan: "현재 계획", billedMonthly: "월별 청구", billedAnnually: "연간 청구", renews: "갱신", freePlanName: "무료", freeIncludes: "무료 플랜 포함 사항：", freeBenefit1: "1회 임대 계약 스캔（평생）", freeBenefit2: "기본 위험 점수 미리보기", freeBenefit3: "3개 파일（100MB 저장소）", freeBenefit4: "읽기 전용 보증금 추적기", upgradeNow: "지금 업그레이드", allActive: "모든 기능 활성화", lineEnabled: "LINE 알림 활성화됨", helpSupport: "도움말 및 지원", helpDesc: "도움이 필요하신가요? 요청을 제출하면 이메일로 답변드립니다", submitRequest: "지원 요청 제출", submitDesc: "문제 보고, 질문 또는 도움 받기", directEmail: "직접 이메일", responseTime: "2-3영업일 내 응답", dataPrivacy: "데이터 프라이버시 및 귀하의 권리", privacyPolicy: "개인정보 보호정책", privacyDesc: "데이터 보호 방법 알아보기", viewPolicy: "정책 보기", exportData: "내 데이터 내보내기", exportDesc: "모든 개인 데이터 다운로드（PDPA 준수）", export: "내보내기", exporting: "내보내는 중...", deleteAccount: "계정을 삭제해야 합니까？", deleteDesc: "계정 및 데이터의 영구 삭제를 요청하려면 등록된 이메일에서 다음 주소로 이메일을 보내주세요", deleteNote: "확인 후 법적 또는 회계 목적으로 특정 기록을 보관해야 하는 경우를 제외하고 14일 이내에 데이터가 삭제됩니다。", preventionBannerTitle: "예방 우선 보호", preventionBannerSubtitle: "임대 계약、보증금 및 문서에 대한 구독 기반 보호", preventionBannerText: "Lease Shield는 명확하고 합법적이며 증거 기반의 임대 관계를 유지하도록 돕습니다。자동 알림、위험 분석 및 전문 템플릿으로 임대 문제를 사전에 예방하세요。", monthly: "월간", annual: "연간", save17: "17% 절약", notificationPreferences: "알림 설정", notificationInsights: "알림 통계", choosePlan: "보호 수준 선택", planDesc: "모든 플랜은 예방과 명확한 기록 유지에 중점을 둡니다", mostPopular: "가장 인기", monthsFree: "2개월 무료", noCreditCard: "신용카드 불필요", perMonth: "/월", save: "절약", currentPlanBadge: "현재 계획", signupFree: "무료로 가입", startPlan: "시작", processing: "처리 중...", monthlyBillingAvailable: "체크아웃 시 월별 결제 가능", save17OnLite: "Lite에서 17% 절약", save17OnProtect: "Protect에서 17% 절약", save17OnSecure: "Secure에서 17% 절약", discountSubtext: "17% 할인 — 연간 결제", logout: "로그아웃", notProvided: "제공되지 않음", manageSubscription: "구독 관리", renewsOn: "갱신 날짜", cancelPlan: "플랜 변경 또는 취소", cancelDialogTitle: "구독을 취소하시겠습니까？", cancelDialogDesc: "떠나시는 것을 유감스럽게 생각합니다。개선을 위해 떠나는 이유를 알려주세요。", cancelReason: "취소 이유", selectReason: "이유 선택", reasonTooExpensive: "너무 비쌉니다", reasonNotUsingEnough: "충분히 사용하지 않음", reasonFoundAlternative: "더 나은 대안을 찾았습니다", reasonMissingFeatures: "필요한 기능이 없음", reasonTechnicalIssues: "기술적 문제", reasonOther: "기타", additionalFeedback: "추가 피드백（선택사항）", feedbackPlaceholder: "개선할 수 있는 부분을 알려주세요...", keepSubscription: "구독 유지", confirmCancel: "취소 확인", cancelling: "처리 중...", whatYoullLose: "잃게 될 것", downgradeNote: "구독은 {date}까지 활성 상태로 유지됩니다。그 후 무료 플랜으로 다운그레이드됩니다。", scheduledCancellation: "취소 예정", cancelScheduledFor: "취소 날짜", reactivate: "구독 재개", landlordInfo: "집주인 정보", landlordInfoDesc: "빠른 알림을 위해 집주인의 연락처 저장", landlordName: "집주인 이름", landlordEmail: "집주인 이메일", landlordPhone: "집주인 전화（WhatsApp）", landlordLine: "집주인 LINE ID", landlordAddress: "집주인 주소", juristicInfo: "관리 사무소 연락처", juristicInfoDesc: "유지보수 알림을 위해 관리 사무소 세부 정보 저장", juristicName: "담당자 이름", juristicEmail: "이메일", juristicPhone: "전화（WhatsApp）", juristicLine: "LINE ID", saveContactInfo: "연락처 정보 저장", connectLineOA: "LINE OA에 연결", connectLineOADesc: "이 링크를 공유하여 Lease Shield 알림에 추가", copyLink: "링크 복사", shareLink: "링크 공유", linkCopied: "링크 복사됨！", orManualEntry: "또는 LINE ID를 수동으로 입력", landlordLineConnect: "집주인을 LINE에 연결", juristicLineConnect: "관리 사무소를 LINE에 연결", showQR: "QR 코드 표시", hideQR: "QR 코드 숨기기", scanQR: "LINE 앱으로 이 QR 코드 스캔", buyCredits: "레터 크레딧 구매", creditBalance: "크레딧 잔액", credits: "크레딧", perCredit: "크레딧당", buyNow: "지금 구매", bestValue: "최고 가치", creditPacks: "크레딧 팩", oneLetterPerCredit: "1편지 = 1크레딧", accessTemplateLibrary: "템플릿 라이브러리 액세스", bilingual: "이중 언어 템플릿", humanAndAiGeneration: "인간 및 AI 생성", creditsNeverExpire: "크레딧은 만료되지 않습니다", purchaseCredits: "크레딧 구매", currentPlanFree: "현재 계획: 무료", freeUpgradeText: "기본 보장 상태입니다. Lite, Protect 또는 Secure로 업그레이드하세요.", chooseBillingInterval: "결제 주기 선택", payMonthly: "월별 결제", payAnnually: "연간 결제", annualSavings: "연간 17% 절약", bestValueBadge: "최고의 가치", proceedToCheckout: "결제 진행", upgradeToSecure: "Secure로 업그레이드", unlockPremium: "프리미엄 기능 잠금 해제", secureFeatures: "연 50회 스캔, 우선 지원 및 연 50개 레터 크레딧", managementOptions: "관리 옵션", managePlan: "플랜 관리", downgradeToFree: "무료로 다운그레이드", keepProtectionActive: "보호를 계속 유지하시겠습니까?", retentionCopy: "다운그레이드하시면 중요한 보호 기능을 잃게 됩니다. 대신 저렴한 요금제로 전환하실 수 있습니다.", switchToLite: "Lite로 전환", continueToFree: "무료 요금제로 계속 진행", confirmDowngradeTitle: "무료 요금제로 다운그레이드", confirmDowngradeWarning: "무제한 임대 스캔, 고급 알림, 추가 레터 크레딧 및 기타 프리미엄 보호 기능을 잃게 됩니다.", reasonForDowngrade: "다운그레이드 이유", goBack: "돌아가기", confirmDowngradeBtn: "무료 요금제 다운그레이드 확인",
    saving: "저장 중...", namePlaceholder: "전체 이름", landlordNamePlaceholder: "집주인 이름", landlordAddressPlaceholder: "집주인 주소", juristicNamePlaceholder: "담당자 이름", appAndSharing: "앱 및 공유", userManualTitle: "Lease Shield 사용자 매뉴얼", userManualDesc: "전체 매뉴얼 다운로드 (DOCX)", userManualDownloaded: "사용자 매뉴얼 다운로드됨", userManualFailed: "매뉴얼 다운로드 실패", installAppTitle: "Lease Shield 앱 설치", installAppDesc: "빠른 액세스를 위해 홈 화면에 추가", shareAppTitle: "친구와 앱 공유", shareAppDesc: "다른 사람들이 보증금을 보호하도록 초대", deleteAccountTitle: "계정 영구 삭제", deleteAccountDesc: "모든 데이터와 계정을 영구적으로 삭제합니다. 이 작업은 취소할 수 없습니다.", dataAndStorage: "데이터 및 저장소", recycleBin: "휴지통", manageDeletedItems: "삭제된 항목 관리", explorerAccount: "탐색 계정", exploringFeatures: "탐색 중", exploringDesc: "탐색 계정을 사용 중입니다. 완전한 보증금 및 유지보수 보호를 위해 Lite, Protect 또는 Secure로 업그레이드하세요.",
    oneTimeScan: "일회성 임대 계약 스캔", oneTimeLabel: "일회성", oneTimePayment: "(일회 결제)", oneTimeUpload: "1회 업로드 + AI 분석", oneTimeReview: "전문가 검토 요약 1건", oneTimeRisk: "위험 점수 1-100", oneTimeTop5: "상위 5개 위험", oneTimeActions: "5가지 권장 조치", oneTimeLetter: "1개 편지 템플릿（필요시）", oneTimeFollowup: "후속 확인 질문 1개", oneTimeNote: "구독 없음, 자동 알림 없음, 저장소 없음", buyOneTimeScan: "일회 스캔 구매", premiumBadge: "프리미엄",
    installInstructions: "설치 방법", iosInstructions: "iPhone/iPad에서:\n1. Safari에서 공유 버튼 탭\n2. '홈 화면에 추가' 탭\n3. '추가' 탭", androidInstructions: "Android에서:\n1. Chrome에서 메뉴 (⋮) 탭\n2. '홈 화면에 추가' 탭\n3. '추가' 탭", desktopInstructions: "데스크톱에서:\n1. 주소 표시줄의 설치 아이콘 클릭\n2. 또는 브라우저 메뉴 > 'Lease Shield 설치'", gotIt: "알겠습니다", install: "설치", alreadyInstalled: "이미 설치됨", comingSoon: "곧 출시",
    exportDialogData: "내보낼 데이터: 프로필, 부동산, 증거 파일, 보증금 추적, 사례 및 알림 설정", formatLabel: "형식:", lineAvailable: "LINE 알림 사용 가능",
    thinkingDowngrade: "다운그레이드를 고려 중이신가요?", downgradeRemovesTools: "다운그레이드하면 주요 보호 도구가 제거되고 위험이 증가합니다.", youWillLose: "잃게 될 것:", advancedReminders: "고급 마감일 알림", fullTracking: "완전한 보증금 및 유지보수 추적", priorityCaseSupport: "우선 사례 지원", additionalScans: "추가 임대 스캔", weakensProtection: "이는 보호를 약화시킵니다. 현재 플랜을 유지하여 권리를 완전히 보호하세요.", keepMyProtection: "내 보호 유지", downgradeAnyway: "다운그레이드 계속",
    liteBestFit: "- 대부분에게 가장 적합", litePriceDesc: "월 ฿190만 - 핵심 보호 유지 및 현재 플랜에서 81% 절약", liteScanBenefit: "연간 6회 임대 계약 스캔", liteEmailBenefit: "이메일 알림", liteTrackingBenefit: "보증금 및 유지보수 추적", signUpToExplore: "등록하여 탐색", cancelNeedTo: "구독을 취소해야 합니까？", manageOrCancel: "구독 관리 또는 취소", upgradeSmarter: "더 스마트하게 업그레이드하세요. 17% 절약. 연간 청구로 1년간 보호를 확보하고 월별 관리를 줄입니다.", equivalent: "해당",
    shareAppText: "Lease Shield로 임대 문제 예방 - 계약 분석, 보증금 추적, 쉬운 사례 개설", shared: "공유됨!", linkCopiedShort: "링크 복사됨!", failedToCopy: "복사 실패", fileSaved: "파일 저장됨", fileShared: "파일 공유 성공", installingApp: "앱 설치 중...", exportFailed: "내보내기 실패. 다시 시도하세요", myLeaseShieldData: "내 Lease Shield 데이터", pricingUnavailable: "가격을 일시적으로 사용할 수 없습니다", tempUnavailable: "일시적으로 사용 불가", checkoutFailed: "결제 생성 실패. 다시 시도하세요", subscriptionFailed: "구독 시작 실패"
  },
  ru: {
    pageTitle: "Мой аккаунт", pageSubtitle: "Управление профилем и подпиской", personalInfo: "Личная информация", editProfile: "Редактировать профиль", fullName: "Полное имя", email: "Email", cannotChange: "Нельзя изменить", phone: "Телефон", phonePlaceholder: "+66 XX XXX XXXX", country: "Страна", countryPlaceholder: "Таиланд", language: "Язык", theme: "Тема", lightMode: "Светлая тема", lightModeShort: "Светлая", darkMode: "Тёмная тема", darkModeShort: "Тёмная", tenantAddress: "Ваш адрес", tenantAddressPlaceholder: "Адрес", tenantCity: "Город", tenantCityPlaceholder: "Бангкок", tenantState: "Регион", tenantStatePlaceholder: "Бангкок", tenantZip: "Почтовый индекс", tenantZipPlaceholder: "10110", saveChanges: "Сохранить изменения", cancel: "Отмена", currentPlan: "Текущий план", billedMonthly: "Ежемесячная оплата", billedAnnually: "Годовая оплата", renews: "Продлевается", freePlanName: "Бесплатно", freeIncludes: "Бесплатный план включает:", freeBenefit1: "1 сканирование договора (навсегда)", freeBenefit2: "Базовый просмотр рисков", freeBenefit3: "3 файла (100MB хранилище)", freeBenefit4: "Отслеживание депозита (только чтение)", upgradeNow: "Обновить сейчас", allActive: "Все функции активны", lineEnabled: "Напоминания LINE включены", helpSupport: "Помощь и поддержка", helpDesc: "Нужна помощь? Отправьте запрос, и мы ответим по email", submitRequest: "Отправить запрос", submitDesc: "Сообщить о проблеме, задать вопрос или получить помощь", directEmail: "Прямой email", responseTime: "Ответ в течение 2-3 рабочих дней", dataPrivacy: "Конфиденциальность данных и ваши права", privacyPolicy: "Политика конфиденциальности", privacyDesc: "Узнайте, как мы защищаем ваши данные", viewPolicy: "Посмотреть политику", exportData: "Экспортировать мои данные", exportDesc: "Скачать все личные данные (соответствует PDPA)", export: "Экспорт", exporting: "Экспорт...", deleteAccount: "Нужно удалить аккаунт?", deleteDesc: "Чтобы запросить окончательное удаление вашей учётной записи и данных, отправьте письмо с зарегистрированного email на", deleteNote: "После проверки ваши данные будут удалены в течение 14 дней, за исключением случаев, когда мы обязаны хранить определённые записи.", preventionBannerTitle: "Защита прежде всего", preventionBannerSubtitle: "Защита на основе подписки для вашего договора, депозита и документов", preventionBannerText: "Lease Shield помогает поддерживать четкие, законные и основанные на доказательствах отношения по аренде. Предотвращайте проблемы до их возникновения.", monthly: "Ежемесячно", annual: "Ежегодно", save17: "Экономия 17%", notificationPreferences: "Настройки уведомлений", notificationInsights: "Статистика уведомлений", choosePlan: "Выберите уровень защиты", planDesc: "Все планы ориентированы на профилактику и ведение четких записей", mostPopular: "САМЫЙ ПОПУЛЯРНЫЙ", monthsFree: "2 МЕСЯЦА БЕСПЛАТНО", noCreditCard: "Кредитная карта не требуется", perMonth: "/месяц", save: "Экономия", currentPlanBadge: "Текущий план", signupFree: "Зарегистрироваться бесплатно", startPlan: "Начать", processing: "Обработка...", monthlyBillingAvailable: "Ежемесячная оплата доступна при оформлении", save17OnLite: "Экономия 17% на Lite", save17OnProtect: "Экономия 17% на Protect", save17OnSecure: "Экономия 17% на Secure", discountSubtext: "Скидка 17% — годовая оплата", logout: "Выход", notProvided: "Не указано", manageSubscription: "Управление подпиской", renewsOn: "Продлевается", cancelPlan: "Изменить или отменить план", cancelDialogTitle: "Отменить подписку?", cancelDialogDesc: "Жаль, что вы уходите. Помогите нам стать лучше, сообщив причину ухода.", cancelReason: "Причина отмены", selectReason: "Выберите причину", reasonTooExpensive: "Слишком дорого", reasonNotUsingEnough: "Недостаточно использую", reasonFoundAlternative: "Нашёл лучшую альтернативу", reasonMissingFeatures: "Отсутствуют нужные функции", reasonTechnicalIssues: "Технические проблемы", reasonOther: "Другое", additionalFeedback: "Дополнительный отзыв (необязательно)", feedbackPlaceholder: "Помогите нам понять, что мы можем улучшить...", keepSubscription: "Оставить подписку", confirmCancel: "Подтвердить отмену", cancelling: "Обработка...", whatYoullLose: "Что вы потеряете", downgradeNote: "Ваша подписка будет активна до {date}. После этого вы будете переведены на бесплатный план.", scheduledCancellation: "Запланирована отмена", cancelScheduledFor: "Отменяется", reactivate: "Возобновить подписку", landlordInfo: "Информация об арендодателе", landlordInfoDesc: "Сохраните контактные данные арендодателя для быстрых уведомлений", landlordName: "Имя арендодателя", landlordEmail: "Email арендодателя", landlordPhone: "Телефон арендодателя (WhatsApp)", landlordLine: "LINE ID арендодателя", landlordAddress: "Адрес арендодателя", juristicInfo: "Контакты управляющей компании", juristicInfoDesc: "Сохраните данные управляющей компании для уведомлений об обслуживании", juristicName: "Имя контактного лица", juristicEmail: "Email", juristicPhone: "Телефон (WhatsApp)", juristicLine: "LINE ID", saveContactInfo: "Сохранить контакты", connectLineOA: "Подключить к LINE OA", connectLineOADesc: "Поделитесь этой ссылкой, чтобы добавить их к уведомлениям Lease Shield", copyLink: "Скопировать ссылку", shareLink: "Поделиться ссылкой", linkCopied: "Ссылка скопирована!", orManualEntry: "Или введите LINE ID вручную", landlordLineConnect: "Подключить арендодателя к LINE", juristicLineConnect: "Подключить управляющую компанию к LINE", showQR: "Показать QR код", hideQR: "Скрыть QR код", scanQR: "Отсканируйте этот QR код в приложении LINE", buyCredits: "Купить кредиты писем", creditBalance: "Баланс кредитов", credits: "Кредиты", perCredit: "за кредит", buyNow: "Купить сейчас", bestValue: "Лучшее предложение", creditPacks: "Пакеты кредитов", oneLetterPerCredit: "1 письмо = 1 кредит", accessTemplateLibrary: "Доступ к библиотеке шаблонов", bilingual: "Двуязычные шаблоны", humanAndAiGeneration: "Создание людьми и ИИ", creditsNeverExpire: "Кредиты не истекают", purchaseCredits: "Купить кредиты", currentPlanFree: "Текущий план: Бесплатно", freeUpgradeText: "У вас базовое покрытие. Обновитесь до Lite, Protect или Secure для полной защиты.", chooseBillingInterval: "Выберите период оплаты", payMonthly: "Платить ежемесячно", payAnnually: "Платить ежегодно", annualSavings: "Экономия 17% в год", bestValueBadge: "Лучшее предложение", proceedToCheckout: "Перейти к оплате", upgradeToSecure: "Обновить до Secure", unlockPremium: "Разблокировать премиум функции", secureFeatures: "50 сканирований/год, приоритетная поддержка и 50 кредитов писем/год", managementOptions: "Опции управления", managePlan: "Управление планом", downgradeToFree: "Понизить до Бесплатного", keepProtectionActive: "Сохранить защиту активной?", retentionCopy: "Вы потеряете важные защитные функции при понижении. Вместо этого можно переключиться на более дешёвый план.", switchToLite: "Переключиться на Lite", continueToFree: "Продолжить на бесплатный план", confirmDowngradeTitle: "Понизить до бесплатного плана", confirmDowngradeWarning: "Вы потеряете неограниченные сканирования договоров, расширенные напоминания, дополнительные кредиты писем и другие премиум функции.", reasonForDowngrade: "Причина понижения", goBack: "Назад", confirmDowngradeBtn: "Подтвердить понижение до бесплатного",
    saving: "Сохранение...", namePlaceholder: "Ваше полное имя", landlordNamePlaceholder: "Имя арендодателя", landlordAddressPlaceholder: "Адрес арендодателя", juristicNamePlaceholder: "Имя контактного лица", appAndSharing: "Приложение и обмен", userManualTitle: "Руководство пользователя Lease Shield", userManualDesc: "Скачать полное руководство (DOCX)", userManualDownloaded: "Руководство загружено", userManualFailed: "Не удалось загрузить руководство", installAppTitle: "Установить приложение Lease Shield", installAppDesc: "Добавьте на главный экран для быстрого доступа", shareAppTitle: "Поделиться приложением с другом", shareAppDesc: "Пригласите других защитить свои депозиты", deleteAccountTitle: "Удалить аккаунт навсегда", deleteAccountDesc: "Окончательно удалите все ваши данные и аккаунт. Это действие нельзя отменить.", dataAndStorage: "Данные и хранилище", recycleBin: "Корзина", manageDeletedItems: "Управление удалёнными элементами", explorerAccount: "Пробный аккаунт", exploringFeatures: "Режим обзора", exploringDesc: "Вы используете пробный аккаунт. Обновитесь до Lite, Protect или Secure для полной защиты депозита и обслуживания.",
    oneTimeScan: "Однократное сканирование договора", oneTimeLabel: "Разово", oneTimePayment: "(одноразовый платёж)", oneTimeUpload: "1 загрузка + AI-анализ", oneTimeReview: "1 экспертный обзор", oneTimeRisk: "Оценка риска 1-100", oneTimeTop5: "Топ-5 рисков", oneTimeActions: "5 рекомендаций", oneTimeLetter: "1 шаблон письма（при необходимости）", oneTimeFollowup: "1 уточняющий вопрос", oneTimeNote: "Без подписки, без автоматических напоминаний, без хранилища", buyOneTimeScan: "Купить одноразовое сканирование", premiumBadge: "ПРЕМИУМ",
    installInstructions: "Инструкция по установке", iosInstructions: "На iPhone/iPad:\n1. Нажмите кнопку Поделиться в Safari\n2. Нажмите 'На экран Домой'\n3. Нажмите 'Добавить'", androidInstructions: "На Android:\n1. Нажмите меню (⋮) в Chrome\n2. Нажмите 'Добавить на главный экран'\n3. Нажмите 'Добавить'", desktopInstructions: "На компьютере:\n1. Нажмите значок установки в адресной строке\n2. Или меню браузера > 'Установить Lease Shield'", gotIt: "Понятно", install: "Установить", alreadyInstalled: "Уже установлено", comingSoon: "Скоро",
    exportDialogData: "Экспортируемые данные: профиль, недвижимость, файлы доказательств, отслеживание депозитов, дела и настройки уведомлений", formatLabel: "Формат:", lineAvailable: "Напоминания LINE доступны",
    thinkingDowngrade: "Думаете о понижении плана?", downgradeRemovesTools: "Понижение плана удалит ключевые инструменты защиты и увеличит ваши риски.", youWillLose: "Вы потеряете:", advancedReminders: "Расширенные напоминания о сроках", fullTracking: "Полное отслеживание депозитов и обслуживания", priorityCaseSupport: "Приоритетная поддержка дел", additionalScans: "Дополнительные сканирования договоров", weakensProtection: "Это ослабляет вашу защиту. Оставайтесь на текущем плане, чтобы полностью защитить свои права.", keepMyProtection: "Сохранить мою защиту", downgradeAnyway: "Всё равно понизить",
    liteBestFit: "- Подходит для большинства", litePriceDesc: "Всего ฿190/месяц - сохраните основную защиту и экономьте 81% от текущего плана", liteScanBenefit: "6 сканирований договоров/год", liteEmailBenefit: "Email уведомления", liteTrackingBenefit: "Отслеживание депозита и обслуживания", signUpToExplore: "Зарегистрироваться", cancelNeedTo: "Нужно отменить подписку?", manageOrCancel: "Управление или отмена подписки", upgradeSmarter: "Обновляйтесь умнее. Экономьте 17%. Годовая оплата фиксирует вашу защиту на год.", equivalent: "Эквивалент",
    shareAppText: "Предотвращайте проблемы аренды с Lease Shield - анализ договоров, отслеживание депозитов, простое открытие дел", shared: "Поделились!", linkCopiedShort: "Ссылка скопирована!", failedToCopy: "Не удалось скопировать", fileSaved: "Файл сохранён", fileShared: "Файл отправлен", installingApp: "Установка приложения...", exportFailed: "Экспорт не удался. Попробуйте снова.", myLeaseShieldData: "Мои данные Lease Shield", pricingUnavailable: "Цена временно недоступна", tempUnavailable: "Временно недоступно", checkoutFailed: "Не удалось создать оплату. Попробуйте снова.", subscriptionFailed: "Не удалось начать подписку"
  }
};

export function getAccountStrings(language) {
  return (accountStrings[language] && typeof accountStrings[language] === 'object') ? accountStrings[language] : accountStrings.en;
}

export default accountStrings;